// Code generated by MockGen. DO NOT EDIT.
// Source: aggregate.go
//
// Generated by this command:
//
//	mockgen -package=event -destination=aggregate_mock.go -source=aggregate.go
//

// Package event is a generated GoMock package.
package event

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBaseAggregate is a mock of BaseAggregate interface.
type MockBaseAggregate struct {
	ctrl     *gomock.Controller
	recorder *MockBaseAggregateMockRecorder
	isgomock struct{}
}

// MockBaseAggregateMockRecorder is the mock recorder for MockBaseAggregate.
type MockBaseAggregateMockRecorder struct {
	mock *MockBaseAggregate
}

// NewMockBaseAggregate creates a new mock instance.
func NewMockBaseAggregate(ctrl *gomock.Controller) *MockBaseAggregate {
	mock := &MockBaseAggregate{ctrl: ctrl}
	mock.recorder = &MockBaseAggregateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseAggregate) EXPECT() *MockBaseAggregateMockRecorder {
	return m.recorder
}

// RegisterEvents mocks base method.
func (m *MockBaseAggregate) RegisterEvents(arg0 RegisterEventsFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterEvents", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterEvents indicates an expected call of RegisterEvents.
func (mr *MockBaseAggregateMockRecorder) RegisterEvents(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEvents", reflect.TypeOf((*MockBaseAggregate)(nil).RegisterEvents), arg0)
}

// MockAggregate is a mock of Aggregate interface.
type MockAggregate struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateMockRecorder
	isgomock struct{}
}

// MockAggregateMockRecorder is the mock recorder for MockAggregate.
type MockAggregateMockRecorder struct {
	mock *MockAggregate
}

// NewMockAggregate creates a new mock instance.
func NewMockAggregate(ctrl *gomock.Controller) *MockAggregate {
	mock := &MockAggregate{ctrl: ctrl}
	mock.recorder = &MockAggregateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregate) EXPECT() *MockAggregateMockRecorder {
	return m.recorder
}

// RegisterEvents mocks base method.
func (m *MockAggregate) RegisterEvents(arg0 RegisterEventsFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterEvents", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterEvents indicates an expected call of RegisterEvents.
func (mr *MockAggregateMockRecorder) RegisterEvents(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEvents", reflect.TypeOf((*MockAggregate)(nil).RegisterEvents), arg0)
}

// Root mocks base method.
func (m *MockAggregate) Root() *AggregateRoot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(*AggregateRoot)
	return ret0
}

// Root indicates an expected call of Root.
func (mr *MockAggregateMockRecorder) Root() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockAggregate)(nil).Root))
}

// Transition mocks base method.
func (m *MockAggregate) Transition(e Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transition indicates an expected call of Transition.
func (mr *MockAggregateMockRecorder) Transition(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockAggregate)(nil).Transition), e)
}
