// Code generated by MockGen. DO NOT EDIT.
// Source: serializer.go
//
// Generated by this command:
//
//	mockgen -package=event -destination=serializer_mock.go -source=serializer.go
//

// Package event is a generated GoMock package.
package event

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSerializer is a mock of Serializer interface.
type MockSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockSerializerMockRecorder
	isgomock struct{}
}

// MockSerializerMockRecorder is the mock recorder for MockSerializer.
type MockSerializerMockRecorder struct {
	mock *MockSerializer
}

// NewMockSerializer creates a new mock instance.
func NewMockSerializer(ctrl *gomock.Controller) *MockSerializer {
	mock := &MockSerializer{ctrl: ctrl}
	mock.recorder = &MockSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSerializer) EXPECT() *MockSerializerMockRecorder {
	return m.recorder
}

// Marshal mocks base method.
func (m *MockSerializer) Marshal(v any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockSerializerMockRecorder) Marshal(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockSerializer)(nil).Marshal), v)
}

// Register mocks base method.
func (m *MockSerializer) Register(agg Aggregate, eventsFunc []eventFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", agg, eventsFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockSerializerMockRecorder) Register(agg, eventsFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSerializer)(nil).Register), agg, eventsFunc)
}

// RegisterAggregate mocks base method.
func (m *MockSerializer) RegisterAggregate(agg BaseAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAggregate", agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAggregate indicates an expected call of RegisterAggregate.
func (mr *MockSerializerMockRecorder) RegisterAggregate(agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAggregate", reflect.TypeOf((*MockSerializer)(nil).RegisterAggregate), agg)
}

// RegisterTypes mocks base method.
func (m *MockSerializer) RegisterTypes(agg Aggregate, eventsFunc ...eventFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{agg}
	for _, a := range eventsFunc {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterTypes", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterTypes indicates an expected call of RegisterTypes.
func (mr *MockSerializerMockRecorder) RegisterTypes(agg any, eventsFunc ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{agg}, eventsFunc...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTypes", reflect.TypeOf((*MockSerializer)(nil).RegisterTypes), varargs...)
}

// ToEventsFunc mocks base method.
func (m *MockSerializer) ToEventsFunc(events ...any) []eventFunc {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ToEventsFunc", varargs...)
	ret0, _ := ret[0].([]eventFunc)
	return ret0
}

// ToEventsFunc indicates an expected call of ToEventsFunc.
func (mr *MockSerializerMockRecorder) ToEventsFunc(events ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToEventsFunc", reflect.TypeOf((*MockSerializer)(nil).ToEventsFunc), events...)
}

// Type mocks base method.
func (m *MockSerializer) Type(typ, name string) (eventFunc, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type", typ, name)
	ret0, _ := ret[0].(eventFunc)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Type indicates an expected call of Type.
func (mr *MockSerializerMockRecorder) Type(typ, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockSerializer)(nil).Type), typ, name)
}

// Unmarshal mocks base method.
func (m *MockSerializer) Unmarshal(data []byte, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockSerializerMockRecorder) Unmarshal(data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockSerializer)(nil).Unmarshal), data, v)
}
