// Code generated by MockGen. DO NOT EDIT.
// Source: webpush.go
//
// Generated by this command:
//
//	mockgen -package=webpush -destination=webpush_mock.go -source=webpush.go
//

// Package webpush is a generated GoMock package.
package webpush

import (
	context "context"
	reflect "reflect"

	webpush "github.com/SherClockHolmes/webpush-go"
	gomock "go.uber.org/mock/gomock"
)

// MockWebPushService is a mock of WebPushService interface.
type MockWebPushService struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushServiceMockRecorder
	isgomock struct{}
}

// MockWebPushServiceMockRecorder is the mock recorder for MockWebPushService.
type MockWebPushServiceMockRecorder struct {
	mock *MockWebPushService
}

// NewMockWebPushService creates a new mock instance.
func NewMockWebPushService(ctrl *gomock.Controller) *MockWebPushService {
	mock := &MockWebPushService{ctrl: ctrl}
	mock.recorder = &MockWebPushServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushService) EXPECT() *MockWebPushServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWebPushService) Send(ctx context.Context, payload []byte, subscription *webpush.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, payload, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWebPushServiceMockRecorder) Send(ctx, payload, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWebPushService)(nil).Send), ctx, payload, subscription)
}
