CREATE TABLE ledger_snapshots (
    id             VARCHAR2(1024) PRIMARY KEY,
    aggregate_id   VARCHAR2(1024) NOT NULL,
    aggregate_type VARCHAR2(255)  NOT NULL,
    version        NUMBER(10)     NOT NULL,
    snapshot_data  CLOB           NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_ledger_snapshots_agg_ver
    ON ledger_snapshots(aggregate_id, aggregate_type, version);

CREATE TABLE ledger_outbox_events (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id   VARCHAR2(1024) NOT NULL,
    aggregate_type VARCHAR2(255)  NOT NULL,
    version        NUMBER(10)     NOT NULL,
    event_name     VARCHAR2(255)  NOT NULL,
    event_data     CLOB           NOT NULL,
    metadata       CLOB           NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_ledger_outbox_aggregate_id
    ON ledger_outbox_events(aggregate_id);
CREATE INDEX idx_ledger_outbox_aggregate_type
    ON ledger_outbox_events(aggregate_type);
CREATE INDEX idx_ledger_outbox_event_name
    ON ledger_outbox_events(event_name);
