CREATE TABLE ledger_transactions (
    transaction_id VARCHAR(1024) PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(1024) NOT NULL,
    account_id VARCHAR(1024) NOT NULL,
    amount BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_ledger_entries_transaction
        FOREIGN KEY (transaction_id) REFERENCES ledger_transactions(transaction_id),
    CONSTRAINT chk_ledger_entries_amount_nonzero CHECK (amount <> 0)
);

CREATE INDEX idx_ledger_entries_account_created ON ledger_entries(account_id, created_at);

CREATE INDEX idx_ledger_entries_transaction_id ON ledger_entries(transaction_id);

CREATE TABLE payment_intents (
    transaction_id VARCHAR(1024) PRIMARY KEY,
    provider VARCHAR(255) NOT NULL,
    external_ref VARCHAR(1024),
    amount BIGINT NOT NULL,
    currency VARCHAR(32) NOT NULL,
    debit_account_id VARCHAR(1024) NOT NULL,
    credit_account_id VARCHAR(1024) NOT NULL,
    status VARCHAR(64) NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_payment_intents_amount_positive CHECK (amount > 0),
    CONSTRAINT uq_payment_intents_provider_ref UNIQUE (provider, external_ref)
);

CREATE TABLE processed_payment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(1024) NOT NULL,
    transaction_id VARCHAR(1024) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_processed_payment_events_provider_key UNIQUE (provider, idempotency_key)
);

CREATE INDEX idx_processed_payment_events_transaction_id ON processed_payment_events(transaction_id);

CREATE OR REPLACE FUNCTION trg_ledger_entries_append_only_fn() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'ledger_entries is append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_ledger_entries_append_only BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION trg_ledger_entries_append_only_fn();
CREATE OR REPLACE FUNCTION trg_ledger_transactions_append_only_fn() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'ledger_transactions is append-only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_ledger_transactions_append_only BEFORE UPDATE OR DELETE ON ledger_transactions FOR EACH ROW EXECUTE FUNCTION trg_ledger_transactions_append_only_fn();
