ALTER TABLE room_members DROP CONSTRAINT fk_room_members_account;
ALTER TABLE messages DROP CONSTRAINT fk_messages_sender;
ALTER TABLE message_receipts DROP CONSTRAINT fk_message_receipts_account;
ALTER TABLE message_deletions DROP CONSTRAINT fk_message_deletions_account;

DROP INDEX IF EXISTS relationship_idx_outbox_unpublished;

ALTER TABLE relationship_outbox_events
    ADD COLUMN version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN event_name VARCHAR(255),
    ADD COLUMN event_data TEXT;

UPDATE relationship_outbox_events
SET
    event_name = event_type,
    event_data = payload::text
WHERE event_name IS NULL
   OR event_data IS NULL;

ALTER TABLE relationship_outbox_events
    ALTER COLUMN event_name SET NOT NULL,
    ALTER COLUMN event_data SET NOT NULL,
    ALTER COLUMN aggregate_id TYPE VARCHAR(1024),
    ALTER COLUMN aggregate_type TYPE VARCHAR(255);

ALTER TABLE relationship_outbox_events
    ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE relationship_outbox_events
    DROP CONSTRAINT IF EXISTS outbox_events_pkey;

ALTER TABLE relationship_outbox_events
    DROP COLUMN id;

ALTER TABLE relationship_outbox_events
    RENAME COLUMN new_id TO id;

ALTER TABLE relationship_outbox_events
    ALTER COLUMN id SET NOT NULL;

ALTER TABLE relationship_outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);

ALTER TABLE relationship_outbox_events
    DROP COLUMN IF EXISTS event_type,
    DROP COLUMN IF EXISTS payload,
    DROP COLUMN IF EXISTS occurred_at,
    DROP COLUMN IF EXISTS published_at;

CREATE INDEX idx_relationship_outbox_created_at
ON relationship_outbox_events (created_at);

CREATE INDEX idx_relationship_outbox_aggregate
ON relationship_outbox_events (aggregate_type, aggregate_id, version);
