// Code generated by MockGen. DO NOT EDIT.
// Source: lock.go
//
// Generated by this command:
//
//	mockgen -package=lock -destination=lock_mock.go -source=lock.go
//

// Package lock is a generated GoMock package.
package lock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLock is a mock of Lock interface.
type MockLock struct {
	ctrl     *gomock.Controller
	recorder *MockLockMockRecorder
	isgomock struct{}
}

// MockLockMockRecorder is the mock recorder for MockLock.
type MockLockMockRecorder struct {
	mock *MockLock
}

// NewMockLock creates a new mock instance.
func NewMockLock(ctrl *gomock.Controller) *MockLock {
	mock := &MockLock{ctrl: ctrl}
	mock.recorder = &MockLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLock) EXPECT() *MockLockMockRecorder {
	return m.recorder
}

// AcquireLock mocks base method.
func (m *MockLock) AcquireLock(ctx context.Context, key, value string, expiration, retryDelay, timeout time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireLock", ctx, key, value, expiration, retryDelay, timeout)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireLock indicates an expected call of AcquireLock.
func (mr *MockLockMockRecorder) AcquireLock(ctx, key, value, expiration, retryDelay, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireLock", reflect.TypeOf((*MockLock)(nil).AcquireLock), ctx, key, value, expiration, retryDelay, timeout)
}

// ReleaseLock mocks base method.
func (m *MockLock) ReleaseLock(ctx context.Context, key, value string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLock", ctx, key, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseLock indicates an expected call of ReleaseLock.
func (mr *MockLockMockRecorder) ReleaseLock(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLock", reflect.TypeOf((*MockLock)(nil).ReleaseLock), ctx, key, value)
}
