// Code generated by MockGen. DO NOT EDIT.
// Source: email_uniqueness.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=email_uniqueness_mock.go -source=email_uniqueness.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailUniquenessChecker is a mock of EmailUniquenessChecker interface.
type MockEmailUniquenessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockEmailUniquenessCheckerMockRecorder
	isgomock struct{}
}

// MockEmailUniquenessCheckerMockRecorder is the mock recorder for MockEmailUniquenessChecker.
type MockEmailUniquenessCheckerMockRecorder struct {
	mock *MockEmailUniquenessChecker
}

// NewMockEmailUniquenessChecker creates a new mock instance.
func NewMockEmailUniquenessChecker(ctrl *gomock.Controller) *MockEmailUniquenessChecker {
	mock := &MockEmailUniquenessChecker{ctrl: ctrl}
	mock.recorder = &MockEmailUniquenessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailUniquenessChecker) EXPECT() *MockEmailUniquenessCheckerMockRecorder {
	return m.recorder
}

// IsEmailExists mocks base method.
func (m *MockEmailUniquenessChecker) IsEmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmailExists indicates an expected call of IsEmailExists.
func (mr *MockEmailUniquenessCheckerMockRecorder) IsEmailExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmailExists", reflect.TypeOf((*MockEmailUniquenessChecker)(nil).IsEmailExists), ctx, email)
}
