// Code generated by MockGen. DO NOT EDIT.
// Source: password_reuse.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=password_reuse_mock.go -source=password_reuse.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasswordReuseChecker is a mock of PasswordReuseChecker interface.
type MockPasswordReuseChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordReuseCheckerMockRecorder
	isgomock struct{}
}

// MockPasswordReuseCheckerMockRecorder is the mock recorder for MockPasswordReuseChecker.
type MockPasswordReuseCheckerMockRecorder struct {
	mock *MockPasswordReuseChecker
}

// NewMockPasswordReuseChecker creates a new mock instance.
func NewMockPasswordReuseChecker(ctrl *gomock.Controller) *MockPasswordReuseChecker {
	mock := &MockPasswordReuseChecker{ctrl: ctrl}
	mock.recorder = &MockPasswordReuseCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordReuseChecker) EXPECT() *MockPasswordReuseCheckerMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockPasswordReuseChecker) Verify(ctx context.Context, val, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, val, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordReuseCheckerMockRecorder) Verify(ctx, val, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordReuseChecker)(nil).Verify), ctx, val, hash)
}
