// Code generated by MockGen. DO NOT EDIT.
// Source: account_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=account_repo_mock.go -source=account_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/room/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomAccountProjectionRepository is a mock of RoomAccountProjectionRepository interface.
type MockRoomAccountProjectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomAccountProjectionRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomAccountProjectionRepositoryMockRecorder is the mock recorder for MockRoomAccountProjectionRepository.
type MockRoomAccountProjectionRepositoryMockRecorder struct {
	mock *MockRoomAccountProjectionRepository
}

// NewMockRoomAccountProjectionRepository creates a new mock instance.
func NewMockRoomAccountProjectionRepository(ctrl *gomock.Controller) *MockRoomAccountProjectionRepository {
	mock := &MockRoomAccountProjectionRepository{ctrl: ctrl}
	mock.recorder = &MockRoomAccountProjectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomAccountProjectionRepository) EXPECT() *MockRoomAccountProjectionRepositoryMockRecorder {
	return m.recorder
}

// ListByAccountIDs mocks base method.
func (m *MockRoomAccountProjectionRepository) ListByAccountIDs(ctx context.Context, accountIDs []string) ([]*entity.AccountEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountIDs", ctx, accountIDs)
	ret0, _ := ret[0].([]*entity.AccountEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountIDs indicates an expected call of ListByAccountIDs.
func (mr *MockRoomAccountProjectionRepositoryMockRecorder) ListByAccountIDs(ctx, accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountIDs", reflect.TypeOf((*MockRoomAccountProjectionRepository)(nil).ListByAccountIDs), ctx, accountIDs)
}

// ProjectAccount mocks base method.
func (m *MockRoomAccountProjectionRepository) ProjectAccount(arg0 context.Context, arg1 *entity.AccountEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectAccount indicates an expected call of ProjectAccount.
func (mr *MockRoomAccountProjectionRepositoryMockRecorder) ProjectAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectAccount", reflect.TypeOf((*MockRoomAccountProjectionRepository)(nil).ProjectAccount), arg0, arg1)
}
