// Code generated by MockGen. DO NOT EDIT.
// Source: room_account_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=account_repo_mock.go -source=room_account_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/room/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomAccountRepository is a mock of RoomAccountRepository interface.
type MockRoomAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomAccountRepositoryMockRecorder is the mock recorder for MockRoomAccountRepository.
type MockRoomAccountRepositoryMockRecorder struct {
	mock *MockRoomAccountRepository
}

// NewMockRoomAccountRepository creates a new mock instance.
func NewMockRoomAccountRepository(ctrl *gomock.Controller) *MockRoomAccountRepository {
	mock := &MockRoomAccountRepository{ctrl: ctrl}
	mock.recorder = &MockRoomAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomAccountRepository) EXPECT() *MockRoomAccountRepositoryMockRecorder {
	return m.recorder
}

// ListByAccountIDs mocks base method.
func (m *MockRoomAccountRepository) ListByAccountIDs(ctx context.Context, accountIDs []string) ([]*entity.AccountEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountIDs", ctx, accountIDs)
	ret0, _ := ret[0].([]*entity.AccountEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountIDs indicates an expected call of ListByAccountIDs.
func (mr *MockRoomAccountRepositoryMockRecorder) ListByAccountIDs(ctx, accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountIDs", reflect.TypeOf((*MockRoomAccountRepository)(nil).ListByAccountIDs), ctx, accountIDs)
}

// ProjectAccount mocks base method.
func (m *MockRoomAccountRepository) ProjectAccount(arg0 context.Context, arg1 *entity.AccountEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectAccount indicates an expected call of ProjectAccount.
func (mr *MockRoomAccountRepositoryMockRecorder) ProjectAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectAccount", reflect.TypeOf((*MockRoomAccountRepository)(nil).ProjectAccount), arg0, arg1)
}
