// Code generated by MockGen. DO NOT EDIT.
// Source: message_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=message_aggregate_repo_mock.go -source=message_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	aggregate "wechat-clone/core/modules/room/domain/aggregate"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageAggregateRepository is a mock of MessageAggregateRepository interface.
type MockMessageAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageAggregateRepositoryMockRecorder is the mock recorder for MockMessageAggregateRepository.
type MockMessageAggregateRepositoryMockRecorder struct {
	mock *MockMessageAggregateRepository
}

// NewMockMessageAggregateRepository creates a new mock instance.
func NewMockMessageAggregateRepository(ctrl *gomock.Controller) *MockMessageAggregateRepository {
	mock := &MockMessageAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockMessageAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageAggregateRepository) EXPECT() *MockMessageAggregateRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockMessageAggregateRepository) Load(ctx context.Context, messageID string) (*aggregate.MessageStateAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, messageID)
	ret0, _ := ret[0].(*aggregate.MessageStateAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockMessageAggregateRepositoryMockRecorder) Load(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockMessageAggregateRepository)(nil).Load), ctx, messageID)
}

// LoadForRecipient mocks base method.
func (m *MockMessageAggregateRepository) LoadForRecipient(ctx context.Context, messageID, recipientAccountID string) (*aggregate.MessageStateAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadForRecipient", ctx, messageID, recipientAccountID)
	ret0, _ := ret[0].(*aggregate.MessageStateAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadForRecipient indicates an expected call of LoadForRecipient.
func (mr *MockMessageAggregateRepositoryMockRecorder) LoadForRecipient(ctx, messageID, recipientAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadForRecipient", reflect.TypeOf((*MockMessageAggregateRepository)(nil).LoadForRecipient), ctx, messageID, recipientAccountID)
}

// Save mocks base method.
func (m *MockMessageAggregateRepository) Save(ctx context.Context, agg *aggregate.MessageStateAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMessageAggregateRepositoryMockRecorder) Save(ctx, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMessageAggregateRepository)(nil).Save), ctx, agg)
}
