// Code generated by MockGen. DO NOT EDIT.
// Source: message_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=message_repo_mock.go -source=message_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/room/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockMessageRepository) CreateMessage(ctx context.Context, message *entity.MessageEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockMessageRepositoryMockRecorder) CreateMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockMessageRepository)(nil).CreateMessage), ctx, message)
}

// GetLastMessageByRoomID mocks base method.
func (m *MockMessageRepository) GetLastMessageByRoomID(ctx context.Context, roomID string) (*entity.MessageEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMessageByRoomID", ctx, roomID)
	ret0, _ := ret[0].(*entity.MessageEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMessageByRoomID indicates an expected call of GetLastMessageByRoomID.
func (mr *MockMessageRepositoryMockRecorder) GetLastMessageByRoomID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMessageByRoomID", reflect.TypeOf((*MockMessageRepository)(nil).GetLastMessageByRoomID), ctx, roomID)
}

// GetMessageByID mocks base method.
func (m *MockMessageRepository) GetMessageByID(ctx context.Context, id string) (*entity.MessageEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, id)
	ret0, _ := ret[0].(*entity.MessageEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageRepositoryMockRecorder) GetMessageByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageRepository)(nil).GetMessageByID), ctx, id)
}

// UpdateMessage mocks base method.
func (m *MockMessageRepository) UpdateMessage(ctx context.Context, message *entity.MessageEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockMessageRepositoryMockRecorder) UpdateMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockMessageRepository)(nil).UpdateMessage), ctx, message)
}
