// Code generated by MockGen. DO NOT EDIT.
// Source: repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=repos_mock.go -source=repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// MessageAggregateRepository mocks base method.
func (m *MockRepos) MessageAggregateRepository() MessageAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageAggregateRepository")
	ret0, _ := ret[0].(MessageAggregateRepository)
	return ret0
}

// MessageAggregateRepository indicates an expected call of MessageAggregateRepository.
func (mr *MockReposMockRecorder) MessageAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageAggregateRepository", reflect.TypeOf((*MockRepos)(nil).MessageAggregateRepository))
}

// RoomAggregateRepository mocks base method.
func (m *MockRepos) RoomAggregateRepository() RoomAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomAggregateRepository")
	ret0, _ := ret[0].(RoomAggregateRepository)
	return ret0
}

// RoomAggregateRepository indicates an expected call of RoomAggregateRepository.
func (mr *MockReposMockRecorder) RoomAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomAggregateRepository", reflect.TypeOf((*MockRepos)(nil).RoomAggregateRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
