// Code generated by MockGen. DO NOT EDIT.
// Source: room_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=room_aggregate_repo_mock.go -source=room_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/room/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomAggregateRepository is a mock of RoomAggregateRepository interface.
type MockRoomAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomAggregateRepositoryMockRecorder is the mock recorder for MockRoomAggregateRepository.
type MockRoomAggregateRepositoryMockRecorder struct {
	mock *MockRoomAggregateRepository
}

// NewMockRoomAggregateRepository creates a new mock instance.
func NewMockRoomAggregateRepository(ctrl *gomock.Controller) *MockRoomAggregateRepository {
	mock := &MockRoomAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockRoomAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomAggregateRepository) EXPECT() *MockRoomAggregateRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRoomAggregateRepository) Delete(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoomAggregateRepositoryMockRecorder) Delete(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoomAggregateRepository)(nil).Delete), ctx, roomID)
}

// Load mocks base method.
func (m *MockRoomAggregateRepository) Load(ctx context.Context, roomID string) (*aggregate.RoomStateAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, roomID)
	ret0, _ := ret[0].(*aggregate.RoomStateAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockRoomAggregateRepositoryMockRecorder) Load(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRoomAggregateRepository)(nil).Load), ctx, roomID)
}

// LoadByDirectKey mocks base method.
func (m *MockRoomAggregateRepository) LoadByDirectKey(ctx context.Context, directKey string) (*aggregate.RoomStateAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByDirectKey", ctx, directKey)
	ret0, _ := ret[0].(*aggregate.RoomStateAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByDirectKey indicates an expected call of LoadByDirectKey.
func (mr *MockRoomAggregateRepositoryMockRecorder) LoadByDirectKey(ctx, directKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByDirectKey", reflect.TypeOf((*MockRoomAggregateRepository)(nil).LoadByDirectKey), ctx, directKey)
}

// Save mocks base method.
func (m *MockRoomAggregateRepository) Save(ctx context.Context, agg *aggregate.RoomStateAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomAggregateRepositoryMockRecorder) Save(ctx, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomAggregateRepository)(nil).Save), ctx, agg)
}
