// Code generated by MockGen. DO NOT EDIT.
// Source: room_outbox_events_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=room_outbox_events_repo_mock.go -source=room_outbox_events_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	event "go-socket/core/shared/pkg/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomOutboxEventsRepository is a mock of RoomOutboxEventsRepository interface.
type MockRoomOutboxEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomOutboxEventsRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomOutboxEventsRepositoryMockRecorder is the mock recorder for MockRoomOutboxEventsRepository.
type MockRoomOutboxEventsRepositoryMockRecorder struct {
	mock *MockRoomOutboxEventsRepository
}

// NewMockRoomOutboxEventsRepository creates a new mock instance.
func NewMockRoomOutboxEventsRepository(ctrl *gomock.Controller) *MockRoomOutboxEventsRepository {
	mock := &MockRoomOutboxEventsRepository{ctrl: ctrl}
	mock.recorder = &MockRoomOutboxEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomOutboxEventsRepository) EXPECT() *MockRoomOutboxEventsRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRoomOutboxEventsRepository) Append(ctx context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRoomOutboxEventsRepositoryMockRecorder) Append(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRoomOutboxEventsRepository)(nil).Append), ctx, arg1)
}
