// Code generated by MockGen. DO NOT EDIT.
// Source: room_member_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=room_member_repo_mock.go -source=room_member_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/room/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomMemberRepository is a mock of RoomMemberRepository interface.
type MockRoomMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomMemberRepositoryMockRecorder is the mock recorder for MockRoomMemberRepository.
type MockRoomMemberRepositoryMockRecorder struct {
	mock *MockRoomMemberRepository
}

// NewMockRoomMemberRepository creates a new mock instance.
func NewMockRoomMemberRepository(ctrl *gomock.Controller) *MockRoomMemberRepository {
	mock := &MockRoomMemberRepository{ctrl: ctrl}
	mock.recorder = &MockRoomMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMemberRepository) EXPECT() *MockRoomMemberRepositoryMockRecorder {
	return m.recorder
}

// CreateRoomMember mocks base method.
func (m *MockRoomMemberRepository) CreateRoomMember(ctx context.Context, roomMember *entity.RoomMemberEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoomMember", ctx, roomMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoomMember indicates an expected call of CreateRoomMember.
func (mr *MockRoomMemberRepositoryMockRecorder) CreateRoomMember(ctx, roomMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoomMember", reflect.TypeOf((*MockRoomMemberRepository)(nil).CreateRoomMember), ctx, roomMember)
}

// DeleteRoomMember mocks base method.
func (m *MockRoomMemberRepository) DeleteRoomMember(ctx context.Context, roomID, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoomMember", ctx, roomID, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoomMember indicates an expected call of DeleteRoomMember.
func (mr *MockRoomMemberRepositoryMockRecorder) DeleteRoomMember(ctx, roomID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoomMember", reflect.TypeOf((*MockRoomMemberRepository)(nil).DeleteRoomMember), ctx, roomID, accountID)
}

// GetRoomMemberByAccount mocks base method.
func (m *MockRoomMemberRepository) GetRoomMemberByAccount(ctx context.Context, roomID, accountID string) (*entity.RoomMemberEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMemberByAccount", ctx, roomID, accountID)
	ret0, _ := ret[0].(*entity.RoomMemberEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomMemberByAccount indicates an expected call of GetRoomMemberByAccount.
func (mr *MockRoomMemberRepositoryMockRecorder) GetRoomMemberByAccount(ctx, roomID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMemberByAccount", reflect.TypeOf((*MockRoomMemberRepository)(nil).GetRoomMemberByAccount), ctx, roomID, accountID)
}

// ListRoomMembers mocks base method.
func (m *MockRoomMemberRepository) ListRoomMembers(ctx context.Context, roomID string) ([]*entity.RoomMemberEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomMembers", ctx, roomID)
	ret0, _ := ret[0].([]*entity.RoomMemberEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomMembers indicates an expected call of ListRoomMembers.
func (mr *MockRoomMemberRepositoryMockRecorder) ListRoomMembers(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomMembers", reflect.TypeOf((*MockRoomMemberRepository)(nil).ListRoomMembers), ctx, roomID)
}

// UpdateRoomMember mocks base method.
func (m *MockRoomMemberRepository) UpdateRoomMember(ctx context.Context, roomMember *entity.RoomMemberEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomMember", ctx, roomMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomMember indicates an expected call of UpdateRoomMember.
func (mr *MockRoomMemberRepositoryMockRecorder) UpdateRoomMember(ctx, roomMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomMember", reflect.TypeOf((*MockRoomMemberRepository)(nil).UpdateRoomMember), ctx, roomMember)
}
