// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -package=providers -destination=provider_mock.go -source=provider.go
//

// Package providers is a generated GoMock package.
package providers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentProvider is a mock of PaymentProvider interface.
type MockPaymentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderMockRecorder
	isgomock struct{}
}

// MockPaymentProviderMockRecorder is the mock recorder for MockPaymentProvider.
type MockPaymentProviderMockRecorder struct {
	mock *MockPaymentProvider
}

// NewMockPaymentProvider creates a new mock instance.
func NewMockPaymentProvider(ctrl *gomock.Controller) *MockPaymentProvider {
	mock := &MockPaymentProvider{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProvider) EXPECT() *MockPaymentProviderMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentProvider) CreatePayment(ctx context.Context, req CreatePaymentRequest) (*CreatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, req)
	ret0, _ := ret[0].(*CreatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentProviderMockRecorder) CreatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentProvider)(nil).CreatePayment), ctx, req)
}

// Name mocks base method.
func (m *MockPaymentProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPaymentProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPaymentProvider)(nil).Name))
}

// ParseEvent mocks base method.
func (m *MockPaymentProvider) ParseEvent(ctx context.Context, event *WebhookEvent) (*PaymentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEvent", ctx, event)
	ret0, _ := ret[0].(*PaymentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEvent indicates an expected call of ParseEvent.
func (mr *MockPaymentProviderMockRecorder) ParseEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEvent", reflect.TypeOf((*MockPaymentProvider)(nil).ParseEvent), ctx, event)
}

// VerifyWebhook mocks base method.
func (m *MockPaymentProvider) VerifyWebhook(ctx context.Context, payload []byte, signature string) (*WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", ctx, payload, signature)
	ret0, _ := ret[0].(*WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockPaymentProviderMockRecorder) VerifyWebhook(ctx, payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockPaymentProvider)(nil).VerifyWebhook), ctx, payload, signature)
}
