// Code generated by MockGen. DO NOT EDIT.
// Source: payment_balance_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=payment_balance_aggregate_repo_mock.go -source=payment_balance_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/payment/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentBalanceAggregateRepository is a mock of PaymentBalanceAggregateRepository interface.
type MockPaymentBalanceAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentBalanceAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentBalanceAggregateRepositoryMockRecorder is the mock recorder for MockPaymentBalanceAggregateRepository.
type MockPaymentBalanceAggregateRepositoryMockRecorder struct {
	mock *MockPaymentBalanceAggregateRepository
}

// NewMockPaymentBalanceAggregateRepository creates a new mock instance.
func NewMockPaymentBalanceAggregateRepository(ctrl *gomock.Controller) *MockPaymentBalanceAggregateRepository {
	mock := &MockPaymentBalanceAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentBalanceAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentBalanceAggregateRepository) EXPECT() *MockPaymentBalanceAggregateRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockPaymentBalanceAggregateRepository) Load(ctx context.Context, accountID string) (*aggregate.PaymentBalanceAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, accountID)
	ret0, _ := ret[0].(*aggregate.PaymentBalanceAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockPaymentBalanceAggregateRepositoryMockRecorder) Load(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockPaymentBalanceAggregateRepository)(nil).Load), ctx, accountID)
}

// Save mocks base method.
func (m *MockPaymentBalanceAggregateRepository) Save(ctx context.Context, arg1 *aggregate.PaymentBalanceAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPaymentBalanceAggregateRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPaymentBalanceAggregateRepository)(nil).Save), ctx, arg1)
}
