// Code generated by MockGen. DO NOT EDIT.
// Source: payment_history_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=payment_history_repo_mock.go -source=payment_history_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/payment/domain/entity"
	utils "go-socket/core/shared/utils"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentHistoryRepository is a mock of PaymentHistoryRepository interface.
type MockPaymentHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentHistoryRepositoryMockRecorder is the mock recorder for MockPaymentHistoryRepository.
type MockPaymentHistoryRepositoryMockRecorder struct {
	mock *MockPaymentHistoryRepository
}

// NewMockPaymentHistoryRepository creates a new mock instance.
func NewMockPaymentHistoryRepository(ctrl *gomock.Controller) *MockPaymentHistoryRepository {
	mock := &MockPaymentHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentHistoryRepository) EXPECT() *MockPaymentHistoryRepositoryMockRecorder {
	return m.recorder
}

// ListPaymentHistory mocks base method.
func (m *MockPaymentHistoryRepository) ListPaymentHistory(ctx context.Context, options utils.QueryOptions) ([]*entity.PaymentHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentHistory", ctx, options)
	ret0, _ := ret[0].([]*entity.PaymentHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentHistory indicates an expected call of ListPaymentHistory.
func (mr *MockPaymentHistoryRepositoryMockRecorder) ListPaymentHistory(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentHistory", reflect.TypeOf((*MockPaymentHistoryRepository)(nil).ListPaymentHistory), ctx, options)
}
