// Code generated by MockGen. DO NOT EDIT.
// Source: payment_projection_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=payment_projection_repo_mock.go -source=payment_projection_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	types "go-socket/core/modules/payment/domain/types"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentProjectionRepository is a mock of PaymentProjectionRepository interface.
type MockPaymentProjectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProjectionRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentProjectionRepositoryMockRecorder is the mock recorder for MockPaymentProjectionRepository.
type MockPaymentProjectionRepositoryMockRecorder struct {
	mock *MockPaymentProjectionRepository
}

// NewMockPaymentProjectionRepository creates a new mock instance.
func NewMockPaymentProjectionRepository(ctrl *gomock.Controller) *MockPaymentProjectionRepository {
	mock := &MockPaymentProjectionRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentProjectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProjectionRepository) EXPECT() *MockPaymentProjectionRepositoryMockRecorder {
	return m.recorder
}

// ProjectTransaction mocks base method.
func (m *MockPaymentProjectionRepository) ProjectTransaction(ctx context.Context, eventID, transactionID, accountID string, amount, balanceDelta int64, transactionType types.TransactionType, createdAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectTransaction", ctx, eventID, transactionID, accountID, amount, balanceDelta, transactionType, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectTransaction indicates an expected call of ProjectTransaction.
func (mr *MockPaymentProjectionRepositoryMockRecorder) ProjectTransaction(ctx, eventID, transactionID, accountID, amount, balanceDelta, transactionType, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectTransaction", reflect.TypeOf((*MockPaymentProjectionRepository)(nil).ProjectTransaction), ctx, eventID, transactionID, accountID, amount, balanceDelta, transactionType, createdAt)
}

// RebuildProjection mocks base method.
func (m *MockPaymentProjectionRepository) RebuildProjection(ctx context.Context, accountID string, mode ProjectionRebuildMode) (*ProjectionRebuildResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildProjection", ctx, accountID, mode)
	ret0, _ := ret[0].(*ProjectionRebuildResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebuildProjection indicates an expected call of RebuildProjection.
func (mr *MockPaymentProjectionRepositoryMockRecorder) RebuildProjection(ctx, accountID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildProjection", reflect.TypeOf((*MockPaymentProjectionRepository)(nil).RebuildProjection), ctx, accountID, mode)
}
