// Code generated by MockGen. DO NOT EDIT.
// Source: payment_outbox_events_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=payment_outbox_events_repo_mock.go -source=payment_outbox_events_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	event "go-socket/core/shared/pkg/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentOutboxEventsRepository is a mock of PaymentOutboxEventsRepository interface.
type MockPaymentOutboxEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentOutboxEventsRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentOutboxEventsRepositoryMockRecorder is the mock recorder for MockPaymentOutboxEventsRepository.
type MockPaymentOutboxEventsRepositoryMockRecorder struct {
	mock *MockPaymentOutboxEventsRepository
}

// NewMockPaymentOutboxEventsRepository creates a new mock instance.
func NewMockPaymentOutboxEventsRepository(ctrl *gomock.Controller) *MockPaymentOutboxEventsRepository {
	mock := &MockPaymentOutboxEventsRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentOutboxEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentOutboxEventsRepository) EXPECT() *MockPaymentOutboxEventsRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockPaymentOutboxEventsRepository) Append(ctx context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockPaymentOutboxEventsRepositoryMockRecorder) Append(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockPaymentOutboxEventsRepository)(nil).Append), ctx, arg1)
}
