// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/payment/domain/repos/payment_intent_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/payment/domain/repos/payment_intent_aggregate_repo_mock.go -source=core/modules/payment/domain/repos/payment_intent_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	aggregate "wechat-clone/core/modules/payment/domain/aggregate"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentIntentAggregateRepo is a mock of PaymentIntentAggregateRepo interface.
type MockPaymentIntentAggregateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentIntentAggregateRepoMockRecorder
	isgomock struct{}
}

// MockPaymentIntentAggregateRepoMockRecorder is the mock recorder for MockPaymentIntentAggregateRepo.
type MockPaymentIntentAggregateRepoMockRecorder struct {
	mock *MockPaymentIntentAggregateRepo
}

// NewMockPaymentIntentAggregateRepo creates a new mock instance.
func NewMockPaymentIntentAggregateRepo(ctrl *gomock.Controller) *MockPaymentIntentAggregateRepo {
	mock := &MockPaymentIntentAggregateRepo{ctrl: ctrl}
	mock.recorder = &MockPaymentIntentAggregateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentIntentAggregateRepo) EXPECT() *MockPaymentIntentAggregateRepoMockRecorder {
	return m.recorder
}

// GetByExternalRef mocks base method.
func (m *MockPaymentIntentAggregateRepo) GetByExternalRef(ctx context.Context, provider, externalRef string) (*aggregate.PaymentIntentAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalRef", ctx, provider, externalRef)
	ret0, _ := ret[0].(*aggregate.PaymentIntentAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalRef indicates an expected call of GetByExternalRef.
func (mr *MockPaymentIntentAggregateRepoMockRecorder) GetByExternalRef(ctx, provider, externalRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalRef", reflect.TypeOf((*MockPaymentIntentAggregateRepo)(nil).GetByExternalRef), ctx, provider, externalRef)
}

// GetByTransactionID mocks base method.
func (m *MockPaymentIntentAggregateRepo) GetByTransactionID(ctx context.Context, transactionID string) (*aggregate.PaymentIntentAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*aggregate.PaymentIntentAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockPaymentIntentAggregateRepoMockRecorder) GetByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockPaymentIntentAggregateRepo)(nil).GetByTransactionID), ctx, transactionID)
}

// ListPendingWithdrawals mocks base method.
func (m *MockPaymentIntentAggregateRepo) ListPendingWithdrawals(ctx context.Context, limit int) ([]*aggregate.PaymentIntentAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingWithdrawals", ctx, limit)
	ret0, _ := ret[0].([]*aggregate.PaymentIntentAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingWithdrawals indicates an expected call of ListPendingWithdrawals.
func (mr *MockPaymentIntentAggregateRepoMockRecorder) ListPendingWithdrawals(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingWithdrawals", reflect.TypeOf((*MockPaymentIntentAggregateRepo)(nil).ListPendingWithdrawals), ctx, limit)
}

// Save mocks base method.
func (m *MockPaymentIntentAggregateRepo) Save(ctx context.Context, arg1 *aggregate.PaymentIntentAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPaymentIntentAggregateRepoMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPaymentIntentAggregateRepo)(nil).Save), ctx, arg1)
}
