// Code generated by MockGen. DO NOT EDIT.
// Source: payment_account_projection_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=payment_account_projection_repo_mock.go -source=payment_account_projection_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/payment/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentAccountProjectionRepository is a mock of PaymentAccountProjectionRepository interface.
type MockPaymentAccountProjectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentAccountProjectionRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentAccountProjectionRepositoryMockRecorder is the mock recorder for MockPaymentAccountProjectionRepository.
type MockPaymentAccountProjectionRepositoryMockRecorder struct {
	mock *MockPaymentAccountProjectionRepository
}

// NewMockPaymentAccountProjectionRepository creates a new mock instance.
func NewMockPaymentAccountProjectionRepository(ctrl *gomock.Controller) *MockPaymentAccountProjectionRepository {
	mock := &MockPaymentAccountProjectionRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentAccountProjectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentAccountProjectionRepository) EXPECT() *MockPaymentAccountProjectionRepositoryMockRecorder {
	return m.recorder
}

// CreateAccountProjection mocks base method.
func (m *MockPaymentAccountProjectionRepository) CreateAccountProjection(ctx context.Context, accountProjection *entity.PaymentAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountProjection", ctx, accountProjection)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccountProjection indicates an expected call of CreateAccountProjection.
func (mr *MockPaymentAccountProjectionRepositoryMockRecorder) CreateAccountProjection(ctx, accountProjection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountProjection", reflect.TypeOf((*MockPaymentAccountProjectionRepository)(nil).CreateAccountProjection), ctx, accountProjection)
}

// DeleteAccountProjection mocks base method.
func (m *MockPaymentAccountProjectionRepository) DeleteAccountProjection(ctx context.Context, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountProjection", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountProjection indicates an expected call of DeleteAccountProjection.
func (mr *MockPaymentAccountProjectionRepositoryMockRecorder) DeleteAccountProjection(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountProjection", reflect.TypeOf((*MockPaymentAccountProjectionRepository)(nil).DeleteAccountProjection), ctx, accountID)
}

// GetAccountProjectionByAccountID mocks base method.
func (m *MockPaymentAccountProjectionRepository) GetAccountProjectionByAccountID(ctx context.Context, accountID string) (*entity.PaymentAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountProjectionByAccountID", ctx, accountID)
	ret0, _ := ret[0].(*entity.PaymentAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountProjectionByAccountID indicates an expected call of GetAccountProjectionByAccountID.
func (mr *MockPaymentAccountProjectionRepositoryMockRecorder) GetAccountProjectionByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountProjectionByAccountID", reflect.TypeOf((*MockPaymentAccountProjectionRepository)(nil).GetAccountProjectionByAccountID), ctx, accountID)
}

// UpdateAccountProjection mocks base method.
func (m *MockPaymentAccountProjectionRepository) UpdateAccountProjection(ctx context.Context, accountProjection *entity.PaymentAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountProjection", ctx, accountProjection)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountProjection indicates an expected call of UpdateAccountProjection.
func (mr *MockPaymentAccountProjectionRepositoryMockRecorder) UpdateAccountProjection(ctx, accountProjection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountProjection", reflect.TypeOf((*MockPaymentAccountProjectionRepository)(nil).UpdateAccountProjection), ctx, accountProjection)
}

// UpsertAccountProjection mocks base method.
func (m *MockPaymentAccountProjectionRepository) UpsertAccountProjection(ctx context.Context, accountProjection *entity.PaymentAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAccountProjection", ctx, accountProjection)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAccountProjection indicates an expected call of UpsertAccountProjection.
func (mr *MockPaymentAccountProjectionRepositoryMockRecorder) UpsertAccountProjection(ctx, accountProjection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAccountProjection", reflect.TypeOf((*MockPaymentAccountProjectionRepository)(nil).UpsertAccountProjection), ctx, accountProjection)
}
