// Code generated by MockGen. DO NOT EDIT.
// Source: provider_payment_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=provider_payment_repo_mock.go -source=provider_payment_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/payment/domain/entity"
	event "go-socket/core/shared/pkg/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProviderPaymentRepository is a mock of ProviderPaymentRepository interface.
type MockProviderPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProviderPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockProviderPaymentRepositoryMockRecorder is the mock recorder for MockProviderPaymentRepository.
type MockProviderPaymentRepositoryMockRecorder struct {
	mock *MockProviderPaymentRepository
}

// NewMockProviderPaymentRepository creates a new mock instance.
func NewMockProviderPaymentRepository(ctrl *gomock.Controller) *MockProviderPaymentRepository {
	mock := &MockProviderPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockProviderPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderPaymentRepository) EXPECT() *MockProviderPaymentRepositoryMockRecorder {
	return m.recorder
}

// CreatePaymentIntent mocks base method.
func (m *MockProviderPaymentRepository) CreatePaymentIntent(ctx context.Context, intent *entity.PaymentIntent, createdEvent event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentIntent", ctx, intent, createdEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePaymentIntent indicates an expected call of CreatePaymentIntent.
func (mr *MockProviderPaymentRepositoryMockRecorder) CreatePaymentIntent(ctx, intent, createdEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentIntent", reflect.TypeOf((*MockProviderPaymentRepository)(nil).CreatePaymentIntent), ctx, intent, createdEvent)
}

// FinalizeSuccessfulPayment mocks base method.
func (m *MockProviderPaymentRepository) FinalizeSuccessfulPayment(ctx context.Context, intent *entity.PaymentIntent, processedEvent *entity.ProcessedPaymentEvent, successEvent event.Event, outboxEvents ...event.Event) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, intent, processedEvent, successEvent}
	for _, a := range outboxEvents {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FinalizeSuccessfulPayment", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeSuccessfulPayment indicates an expected call of FinalizeSuccessfulPayment.
func (mr *MockProviderPaymentRepositoryMockRecorder) FinalizeSuccessfulPayment(ctx, intent, processedEvent, successEvent any, outboxEvents ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, intent, processedEvent, successEvent}, outboxEvents...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeSuccessfulPayment", reflect.TypeOf((*MockProviderPaymentRepository)(nil).FinalizeSuccessfulPayment), varargs...)
}

// GetIntentByExternalRef mocks base method.
func (m *MockProviderPaymentRepository) GetIntentByExternalRef(ctx context.Context, provider, externalRef string) (*entity.PaymentIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntentByExternalRef", ctx, provider, externalRef)
	ret0, _ := ret[0].(*entity.PaymentIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntentByExternalRef indicates an expected call of GetIntentByExternalRef.
func (mr *MockProviderPaymentRepositoryMockRecorder) GetIntentByExternalRef(ctx, provider, externalRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntentByExternalRef", reflect.TypeOf((*MockProviderPaymentRepository)(nil).GetIntentByExternalRef), ctx, provider, externalRef)
}

// GetIntentByTransactionID mocks base method.
func (m *MockProviderPaymentRepository) GetIntentByTransactionID(ctx context.Context, transactionID string) (*entity.PaymentIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntentByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*entity.PaymentIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntentByTransactionID indicates an expected call of GetIntentByTransactionID.
func (mr *MockProviderPaymentRepositoryMockRecorder) GetIntentByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntentByTransactionID", reflect.TypeOf((*MockProviderPaymentRepository)(nil).GetIntentByTransactionID), ctx, transactionID)
}

// IsProcessed mocks base method.
func (m *MockProviderPaymentRepository) IsProcessed(ctx context.Context, provider, idempotencyKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessed", ctx, provider, idempotencyKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProcessed indicates an expected call of IsProcessed.
func (mr *MockProviderPaymentRepositoryMockRecorder) IsProcessed(ctx, provider, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessed", reflect.TypeOf((*MockProviderPaymentRepository)(nil).IsProcessed), ctx, provider, idempotencyKey)
}

// SavePaymentIntent mocks base method.
func (m *MockProviderPaymentRepository) SavePaymentIntent(ctx context.Context, intent *entity.PaymentIntent, outboxEvents ...event.Event) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, intent}
	for _, a := range outboxEvents {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SavePaymentIntent", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePaymentIntent indicates an expected call of SavePaymentIntent.
func (mr *MockProviderPaymentRepositoryMockRecorder) SavePaymentIntent(ctx, intent any, outboxEvents ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, intent}, outboxEvents...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePaymentIntent", reflect.TypeOf((*MockProviderPaymentRepository)(nil).SavePaymentIntent), varargs...)
}
