// Code generated by MockGen. DO NOT EDIT.
// Source: repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=repos_mock.go -source=repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// PaymentAccountProjectionRepository mocks base method.
func (m *MockRepos) PaymentAccountProjectionRepository() PaymentAccountProjectionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentAccountProjectionRepository")
	ret0, _ := ret[0].(PaymentAccountProjectionRepository)
	return ret0
}

// PaymentAccountProjectionRepository indicates an expected call of PaymentAccountProjectionRepository.
func (mr *MockReposMockRecorder) PaymentAccountProjectionRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentAccountProjectionRepository", reflect.TypeOf((*MockRepos)(nil).PaymentAccountProjectionRepository))
}

// PaymentBalanceAggregateRepository mocks base method.
func (m *MockRepos) PaymentBalanceAggregateRepository() PaymentBalanceAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentBalanceAggregateRepository")
	ret0, _ := ret[0].(PaymentBalanceAggregateRepository)
	return ret0
}

// PaymentBalanceAggregateRepository indicates an expected call of PaymentBalanceAggregateRepository.
func (mr *MockReposMockRecorder) PaymentBalanceAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentBalanceAggregateRepository", reflect.TypeOf((*MockRepos)(nil).PaymentBalanceAggregateRepository))
}

// PaymentHistoryRepository mocks base method.
func (m *MockRepos) PaymentHistoryRepository() PaymentHistoryRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentHistoryRepository")
	ret0, _ := ret[0].(PaymentHistoryRepository)
	return ret0
}

// PaymentHistoryRepository indicates an expected call of PaymentHistoryRepository.
func (mr *MockReposMockRecorder) PaymentHistoryRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentHistoryRepository", reflect.TypeOf((*MockRepos)(nil).PaymentHistoryRepository))
}

// PaymentOutboxEventsRepository mocks base method.
func (m *MockRepos) PaymentOutboxEventsRepository() PaymentOutboxEventsRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentOutboxEventsRepository")
	ret0, _ := ret[0].(PaymentOutboxEventsRepository)
	return ret0
}

// PaymentOutboxEventsRepository indicates an expected call of PaymentOutboxEventsRepository.
func (mr *MockReposMockRecorder) PaymentOutboxEventsRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentOutboxEventsRepository", reflect.TypeOf((*MockRepos)(nil).PaymentOutboxEventsRepository))
}

// PaymentProjectionRepository mocks base method.
func (m *MockRepos) PaymentProjectionRepository() PaymentProjectionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentProjectionRepository")
	ret0, _ := ret[0].(PaymentProjectionRepository)
	return ret0
}

// PaymentProjectionRepository indicates an expected call of PaymentProjectionRepository.
func (mr *MockReposMockRecorder) PaymentProjectionRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentProjectionRepository", reflect.TypeOf((*MockRepos)(nil).PaymentProjectionRepository))
}

// ProviderPaymentRepository mocks base method.
func (m *MockRepos) ProviderPaymentRepository() ProviderPaymentRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderPaymentRepository")
	ret0, _ := ret[0].(ProviderPaymentRepository)
	return ret0
}

// ProviderPaymentRepository indicates an expected call of ProviderPaymentRepository.
func (mr *MockReposMockRecorder) ProviderPaymentRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderPaymentRepository", reflect.TypeOf((*MockRepos)(nil).ProviderPaymentRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
