// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -package=discovery -destination=client_mock.go -source=client.go
//

// Package discovery is a generated GoMock package.
package discovery

import (
	context "context"
	reflect "reflect"

	api "github.com/hashicorp/consul/api"
	gomock "go.uber.org/mock/gomock"
)

// MockConsulClient is a mock of ConsulClient interface.
type MockConsulClient struct {
	ctrl     *gomock.Controller
	recorder *MockConsulClientMockRecorder
	isgomock struct{}
}

// MockConsulClientMockRecorder is the mock recorder for MockConsulClient.
type MockConsulClientMockRecorder struct {
	mock *MockConsulClient
}

// NewMockConsulClient creates a new mock instance.
func NewMockConsulClient(ctrl *gomock.Controller) *MockConsulClient {
	mock := &MockConsulClient{ctrl: ctrl}
	mock.recorder = &MockConsulClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulClient) EXPECT() *MockConsulClientMockRecorder {
	return m.recorder
}

// GetService mocks base method.
func (m *MockConsulClient) GetService(ctx context.Context, serviceID string) (*api.AgentService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", ctx, serviceID)
	ret0, _ := ret[0].(*api.AgentService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockConsulClientMockRecorder) GetService(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockConsulClient)(nil).GetService), ctx, serviceID)
}

// GetServiceHealth mocks base method.
func (m *MockConsulClient) GetServiceHealth(ctx context.Context, serviceID string) ([]*api.HealthCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceHealth", ctx, serviceID)
	ret0, _ := ret[0].([]*api.HealthCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceHealth indicates an expected call of GetServiceHealth.
func (mr *MockConsulClientMockRecorder) GetServiceHealth(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceHealth", reflect.TypeOf((*MockConsulClient)(nil).GetServiceHealth), ctx, serviceID)
}

// GetServices mocks base method.
func (m *MockConsulClient) GetServices(ctx context.Context) ([]*api.AgentService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", ctx)
	ret0, _ := ret[0].([]*api.AgentService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockConsulClientMockRecorder) GetServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockConsulClient)(nil).GetServices), ctx)
}

// RegisterService mocks base method.
func (m *MockConsulClient) RegisterService(ctx context.Context, serviceID, serviceName, serviceAddress string, servicePort int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterService", ctx, serviceID, serviceName, serviceAddress, servicePort)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterService indicates an expected call of RegisterService.
func (mr *MockConsulClientMockRecorder) RegisterService(ctx, serviceID, serviceName, serviceAddress, servicePort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterService", reflect.TypeOf((*MockConsulClient)(nil).RegisterService), ctx, serviceID, serviceName, serviceAddress, servicePort)
}

// UnregisterService mocks base method.
func (m *MockConsulClient) UnregisterService(ctx context.Context, serviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterService", ctx, serviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterService indicates an expected call of UnregisterService.
func (mr *MockConsulClientMockRecorder) UnregisterService(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterService", reflect.TypeOf((*MockConsulClient)(nil).UnregisterService), ctx, serviceID)
}
