// Code generated by MockGen. DO NOT EDIT.
// Source: aggregate_event_store.go
//
// Generated by this command:
//
//	mockgen -package=eventstore -destination=aggregate_event_store_mock.go -source=aggregate_event_store.go
//

// Package eventstore is a generated GoMock package.
package eventstore

import (
	context "context"
	reflect "reflect"
	event "wechat-clone/core/shared/pkg/event"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerEventStore is a mock of LedgerEventStore interface.
type MockLedgerEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerEventStoreMockRecorder
	isgomock struct{}
}

// MockLedgerEventStoreMockRecorder is the mock recorder for MockLedgerEventStore.
type MockLedgerEventStoreMockRecorder struct {
	mock *MockLedgerEventStore
}

// NewMockLedgerEventStore creates a new mock instance.
func NewMockLedgerEventStore(ctrl *gomock.Controller) *MockLedgerEventStore {
	mock := &MockLedgerEventStore{ctrl: ctrl}
	mock.recorder = &MockLedgerEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerEventStore) EXPECT() *MockLedgerEventStoreMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockLedgerEventStore) Append(ctx context.Context, evt event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockLedgerEventStoreMockRecorder) Append(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockLedgerEventStore)(nil).Append), ctx, evt)
}

// CheckAndUpdateVersion mocks base method.
func (m *MockLedgerEventStore) CheckAndUpdateVersion(ctx context.Context, aggregateID, aggregateType string, baseVersion, newVersion int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndUpdateVersion", ctx, aggregateID, aggregateType, baseVersion, newVersion)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndUpdateVersion indicates an expected call of CheckAndUpdateVersion.
func (mr *MockLedgerEventStoreMockRecorder) CheckAndUpdateVersion(ctx, aggregateID, aggregateType, baseVersion, newVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndUpdateVersion", reflect.TypeOf((*MockLedgerEventStore)(nil).CheckAndUpdateVersion), ctx, aggregateID, aggregateType, baseVersion, newVersion)
}

// CreateIfNotExist mocks base method.
func (m *MockLedgerEventStore) CreateIfNotExist(ctx context.Context, aggregateID, aggregateType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfNotExist", ctx, aggregateID, aggregateType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIfNotExist indicates an expected call of CreateIfNotExist.
func (mr *MockLedgerEventStoreMockRecorder) CreateIfNotExist(ctx, aggregateID, aggregateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfNotExist", reflect.TypeOf((*MockLedgerEventStore)(nil).CreateIfNotExist), ctx, aggregateID, aggregateType)
}

// CreateSnapshot mocks base method.
func (m *MockLedgerEventStore) CreateSnapshot(ctx context.Context, agg event.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockLedgerEventStoreMockRecorder) CreateSnapshot(ctx, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockLedgerEventStore)(nil).CreateSnapshot), ctx, agg)
}

// Get mocks base method.
func (m *MockLedgerEventStore) Get(ctx context.Context, aggregateID, aggregateType string, afterVersion int, agg event.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, aggregateID, aggregateType, afterVersion, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockLedgerEventStoreMockRecorder) Get(ctx, aggregateID, aggregateType, afterVersion, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLedgerEventStore)(nil).Get), ctx, aggregateID, aggregateType, afterVersion, agg)
}

// ReadSnapshot mocks base method.
func (m *MockLedgerEventStore) ReadSnapshot(ctx context.Context, aggregateID, aggregateType string, agg event.Aggregate) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSnapshot", ctx, aggregateID, aggregateType, agg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSnapshot indicates an expected call of ReadSnapshot.
func (mr *MockLedgerEventStoreMockRecorder) ReadSnapshot(ctx, aggregateID, aggregateType, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSnapshot", reflect.TypeOf((*MockLedgerEventStore)(nil).ReadSnapshot), ctx, aggregateID, aggregateType, agg)
}

// MockLedgerPostingStore is a mock of LedgerPostingStore interface.
type MockLedgerPostingStore struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerPostingStoreMockRecorder
	isgomock struct{}
}

// MockLedgerPostingStoreMockRecorder is the mock recorder for MockLedgerPostingStore.
type MockLedgerPostingStoreMockRecorder struct {
	mock *MockLedgerPostingStore
}

// NewMockLedgerPostingStore creates a new mock instance.
func NewMockLedgerPostingStore(ctrl *gomock.Controller) *MockLedgerPostingStore {
	mock := &MockLedgerPostingStore{ctrl: ctrl}
	mock.recorder = &MockLedgerPostingStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerPostingStore) EXPECT() *MockLedgerPostingStoreMockRecorder {
	return m.recorder
}

// ReservePostedTransaction mocks base method.
func (m *MockLedgerPostingStore) ReservePostedTransaction(ctx context.Context, evt event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReservePostedTransaction", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReservePostedTransaction indicates an expected call of ReservePostedTransaction.
func (mr *MockLedgerPostingStoreMockRecorder) ReservePostedTransaction(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReservePostedTransaction", reflect.TypeOf((*MockLedgerPostingStore)(nil).ReservePostedTransaction), ctx, evt)
}
