// Code generated by MockGen. DO NOT EDIT.
// Source: aggregate_store.go
//
// Generated by this command:
//
//	mockgen -package=eventstore -destination=aggregate_store_mock.go -source=aggregate_store.go
//

// Package eventstore is a generated GoMock package.
package eventstore

import (
	context "context"
	reflect "reflect"
	event "wechat-clone/core/shared/pkg/event"

	gomock "go.uber.org/mock/gomock"
)

// MockAggregateStore is a mock of AggregateStore interface.
type MockAggregateStore struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateStoreMockRecorder
	isgomock struct{}
}

// MockAggregateStoreMockRecorder is the mock recorder for MockAggregateStore.
type MockAggregateStoreMockRecorder struct {
	mock *MockAggregateStore
}

// NewMockAggregateStore creates a new mock instance.
func NewMockAggregateStore(ctrl *gomock.Controller) *MockAggregateStore {
	mock := &MockAggregateStore{ctrl: ctrl}
	mock.recorder = &MockAggregateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateStore) EXPECT() *MockAggregateStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAggregateStore) Get(ctx context.Context, aggregateID string, agg event.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, aggregateID, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockAggregateStoreMockRecorder) Get(ctx, aggregateID, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAggregateStore)(nil).Get), ctx, aggregateID, agg)
}

// Save mocks base method.
func (m *MockAggregateStore) Save(ctx context.Context, agg event.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAggregateStoreMockRecorder) Save(ctx, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAggregateStore)(nil).Save), ctx, agg)
}
