// Code generated by MockGen. DO NOT EDIT.
// Source: account_projection_repository.go
//
// Generated by this command:
//
//	mockgen -package=messaging -destination=account_projection_repository_mock.go -source=account_projection_repository.go
//

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/relationship/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountProjectionRepository is a mock of AccountProjectionRepository interface.
type MockAccountProjectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountProjectionRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountProjectionRepositoryMockRecorder is the mock recorder for MockAccountProjectionRepository.
type MockAccountProjectionRepositoryMockRecorder struct {
	mock *MockAccountProjectionRepository
}

// NewMockAccountProjectionRepository creates a new mock instance.
func NewMockAccountProjectionRepository(ctrl *gomock.Controller) *MockAccountProjectionRepository {
	mock := &MockAccountProjectionRepository{ctrl: ctrl}
	mock.recorder = &MockAccountProjectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountProjectionRepository) EXPECT() *MockAccountProjectionRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAccountProjectionRepository) GetByID(ctx context.Context, accountID string) (*entity.AccountProjection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, accountID)
	ret0, _ := ret[0].(*entity.AccountProjection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountProjectionRepositoryMockRecorder) GetByID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountProjectionRepository)(nil).GetByID), ctx, accountID)
}

// ProjectAccount mocks base method.
func (m *MockAccountProjectionRepository) ProjectAccount(ctx context.Context, account *entity.AccountProjection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectAccount indicates an expected call of ProjectAccount.
func (mr *MockAccountProjectionRepositoryMockRecorder) ProjectAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectAccount", reflect.TypeOf((*MockAccountProjectionRepository)(nil).ProjectAccount), ctx, account)
}
