// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -package=storage -destination=storage_mock.go -source=storage.go
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// PresignedGetObjectURL mocks base method.
func (m *MockStorage) PresignedGetObjectURL(ctx context.Context, objectKey string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedGetObjectURL", ctx, objectKey, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedGetObjectURL indicates an expected call of PresignedGetObjectURL.
func (mr *MockStorageMockRecorder) PresignedGetObjectURL(ctx, objectKey, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedGetObjectURL", reflect.TypeOf((*MockStorage)(nil).PresignedGetObjectURL), ctx, objectKey, expiry)
}

// PresignedPutObjectURL mocks base method.
func (m *MockStorage) PresignedPutObjectURL(ctx context.Context, objectKey string, expiry time.Duration) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedPutObjectURL", ctx, objectKey, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PresignedPutObjectURL indicates an expected call of PresignedPutObjectURL.
func (mr *MockStorageMockRecorder) PresignedPutObjectURL(ctx, objectKey, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedPutObjectURL", reflect.TypeOf((*MockStorage)(nil).PresignedPutObjectURL), ctx, objectKey, expiry)
}
