// Code generated by MockGen. DO NOT EDIT.
// Source: repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=repos_mock.go -source=repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// FriendRequestAggregateRepository mocks base method.
func (m *MockRepos) FriendRequestAggregateRepository() FriendRequestAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FriendRequestAggregateRepository")
	ret0, _ := ret[0].(FriendRequestAggregateRepository)
	return ret0
}

// FriendRequestAggregateRepository indicates an expected call of FriendRequestAggregateRepository.
func (mr *MockReposMockRecorder) FriendRequestAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FriendRequestAggregateRepository", reflect.TypeOf((*MockRepos)(nil).FriendRequestAggregateRepository))
}

// RelationshipPairAggregateRepository mocks base method.
func (m *MockRepos) RelationshipPairAggregateRepository() RelationshipPairAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelationshipPairAggregateRepository")
	ret0, _ := ret[0].(RelationshipPairAggregateRepository)
	return ret0
}

// RelationshipPairAggregateRepository indicates an expected call of RelationshipPairAggregateRepository.
func (mr *MockReposMockRecorder) RelationshipPairAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelationshipPairAggregateRepository", reflect.TypeOf((*MockRepos)(nil).RelationshipPairAggregateRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
