// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/ledger/application/projection/read_repo.go
//
// Generated by this command:
//
//	mockgen -package=projection -destination=core/modules/ledger/application/projection/read_repo_mock.go -source=core/modules/ledger/application/projection/read_repo.go
//

// Package projection is a generated GoMock package.
package projection

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/ledger/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockReadRepository is a mock of ReadRepository interface.
type MockReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReadRepositoryMockRecorder
	isgomock struct{}
}

// MockReadRepositoryMockRecorder is the mock recorder for MockReadRepository.
type MockReadRepositoryMockRecorder struct {
	mock *MockReadRepository
}

// NewMockReadRepository creates a new mock instance.
func NewMockReadRepository(ctrl *gomock.Controller) *MockReadRepository {
	mock := &MockReadRepository{ctrl: ctrl}
	mock.recorder = &MockReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRepository) EXPECT() *MockReadRepositoryMockRecorder {
	return m.recorder
}

// CountTransactions mocks base method.
func (m *MockReadRepository) CountTransactions(ctx context.Context, accountID, currency string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTransactions", ctx, accountID, currency)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTransactions indicates an expected call of CountTransactions.
func (mr *MockReadRepositoryMockRecorder) CountTransactions(ctx, accountID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTransactions", reflect.TypeOf((*MockReadRepository)(nil).CountTransactions), ctx, accountID, currency)
}

// GetBalance mocks base method.
func (m *MockReadRepository) GetBalance(ctx context.Context, accountID, currency string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID, currency)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockReadRepositoryMockRecorder) GetBalance(ctx, accountID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockReadRepository)(nil).GetBalance), ctx, accountID, currency)
}

// GetTransaction mocks base method.
func (m *MockReadRepository) GetTransaction(ctx context.Context, transactionID string) (*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, transactionID)
	ret0, _ := ret[0].(*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockReadRepositoryMockRecorder) GetTransaction(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockReadRepository)(nil).GetTransaction), ctx, transactionID)
}

// ListTransactions mocks base method.
func (m *MockReadRepository) ListTransactions(ctx context.Context, filter ListTransactionsFilter) ([]*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, filter)
	ret0, _ := ret[0].([]*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockReadRepositoryMockRecorder) ListTransactions(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockReadRepository)(nil).ListTransactions), ctx, filter)
}

// ProjectTransaction mocks base method.
func (m *MockReadRepository) ProjectTransaction(ctx context.Context, transaction *LedgerTransactionProjected) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectTransaction", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectTransaction indicates an expected call of ProjectTransaction.
func (mr *MockReadRepositoryMockRecorder) ProjectTransaction(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectTransaction", reflect.TypeOf((*MockReadRepository)(nil).ProjectTransaction), ctx, transaction)
}
