// Code generated by MockGen. DO NOT EDIT.
// Source: account_cache.go
//
// Generated by this command:
//
//	mockgen -package=cache -destination=account_cache_mock.go -source=account_cache.go
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	entity "go-socket/core/modules/account/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountCache is a mock of AccountCache interface.
type MockAccountCache struct {
	ctrl     *gomock.Controller
	recorder *MockAccountCacheMockRecorder
	isgomock struct{}
}

// MockAccountCacheMockRecorder is the mock recorder for MockAccountCache.
type MockAccountCacheMockRecorder struct {
	mock *MockAccountCache
}

// NewMockAccountCache creates a new mock instance.
func NewMockAccountCache(ctrl *gomock.Controller) *MockAccountCache {
	mock := &MockAccountCache{ctrl: ctrl}
	mock.recorder = &MockAccountCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountCache) EXPECT() *MockAccountCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAccountCache) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountCacheMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountCache)(nil).Delete), ctx, id)
}

// DeleteByEmail mocks base method.
func (m *MockAccountCache) DeleteByEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEmail indicates an expected call of DeleteByEmail.
func (mr *MockAccountCacheMockRecorder) DeleteByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEmail", reflect.TypeOf((*MockAccountCache)(nil).DeleteByEmail), ctx, email)
}

// Get mocks base method.
func (m *MockAccountCache) Get(ctx context.Context, id string) (*entity.Account, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Account)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAccountCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAccountCache)(nil).Get), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockAccountCache) GetByEmail(ctx context.Context, email string) (*entity.Account, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.Account)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockAccountCacheMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockAccountCache)(nil).GetByEmail), ctx, email)
}

// Set mocks base method.
func (m_2 *MockAccountCache) Set(ctx context.Context, m *entity.Account) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Set", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockAccountCacheMockRecorder) Set(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAccountCache)(nil).Set), ctx, m)
}

// SetByEmail mocks base method.
func (m_2 *MockAccountCache) SetByEmail(ctx context.Context, m *entity.Account) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SetByEmail", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetByEmail indicates an expected call of SetByEmail.
func (mr *MockAccountCacheMockRecorder) SetByEmail(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetByEmail", reflect.TypeOf((*MockAccountCache)(nil).SetByEmail), ctx, m)
}
