// Code generated by MockGen. DO NOT EDIT.
// Source: account_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=account_service_mock.go -source=account_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	aggregate "go-socket/core/modules/account/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountService is a mock of AccountService interface.
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
	isgomock struct{}
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService.
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance.
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// LoadAccountAggregate mocks base method.
func (m *MockAccountService) LoadAccountAggregate(ctx context.Context, accountID string) (*aggregate.AccountAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAccountAggregate", ctx, accountID)
	ret0, _ := ret[0].(*aggregate.AccountAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAccountAggregate indicates an expected call of LoadAccountAggregate.
func (mr *MockAccountServiceMockRecorder) LoadAccountAggregate(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAccountAggregate", reflect.TypeOf((*MockAccountService)(nil).LoadAccountAggregate), ctx, accountID)
}
