// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/account/application/service/email_verification_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=core/modules/account/application/service/email_verification_service_mock.go -source=core/modules/account/application/service/email_verification_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"
	entity "wechat-clone/core/modules/account/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMailer) Send(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMailerMockRecorder) Send(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMailer)(nil).Send), ctx, to, subject, body)
}

// SendTemplate mocks base method.
func (m *MockMailer) SendTemplate(ctx context.Context, to, subject, templateName string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplate", ctx, to, subject, templateName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTemplate indicates an expected call of SendTemplate.
func (mr *MockMailerMockRecorder) SendTemplate(ctx, to, subject, templateName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplate", reflect.TypeOf((*MockMailer)(nil).SendTemplate), ctx, to, subject, templateName, data)
}

// MockEmailVerificationService is a mock of EmailVerificationService interface.
type MockEmailVerificationService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationServiceMockRecorder
	isgomock struct{}
}

// MockEmailVerificationServiceMockRecorder is the mock recorder for MockEmailVerificationService.
type MockEmailVerificationServiceMockRecorder struct {
	mock *MockEmailVerificationService
}

// NewMockEmailVerificationService creates a new mock instance.
func NewMockEmailVerificationService(ctrl *gomock.Controller) *MockEmailVerificationService {
	mock := &MockEmailVerificationService{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationService) EXPECT() *MockEmailVerificationServiceMockRecorder {
	return m.recorder
}

// ConsumeVerificationToken mocks base method.
func (m *MockEmailVerificationService) ConsumeVerificationToken(ctx context.Context, token string) (*EmailVerificationTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeVerificationToken", ctx, token)
	ret0, _ := ret[0].(*EmailVerificationTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeVerificationToken indicates an expected call of ConsumeVerificationToken.
func (mr *MockEmailVerificationServiceMockRecorder) ConsumeVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeVerificationToken", reflect.TypeOf((*MockEmailVerificationService)(nil).ConsumeVerificationToken), ctx, token)
}

// SendVerificationEmail mocks base method.
func (m *MockEmailVerificationService) SendVerificationEmail(ctx context.Context, account *entity.Account) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockEmailVerificationServiceMockRecorder) SendVerificationEmail(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockEmailVerificationService)(nil).SendVerificationEmail), ctx, account)
}
