// Code generated by MockGen. DO NOT EDIT.
// Source: registration_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=registration_service_mock.go -source=registration_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockRegistrationService) Register(ctx context.Context, command RegisterAccountCommand) (*RegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, command)
	ret0, _ := ret[0].(*RegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockRegistrationServiceMockRecorder) Register(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRegistrationService)(nil).Register), ctx, command)
}
