// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=services_mock.go -source=services.go
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServices is a mock of Services interface.
type MockServices struct {
	ctrl     *gomock.Controller
	recorder *MockServicesMockRecorder
	isgomock struct{}
}

// MockServicesMockRecorder is the mock recorder for MockServices.
type MockServicesMockRecorder struct {
	mock *MockServices
}

// NewMockServices creates a new mock instance.
func NewMockServices(ctrl *gomock.Controller) *MockServices {
	mock := &MockServices{ctrl: ctrl}
	mock.recorder = &MockServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServices) EXPECT() *MockServicesMockRecorder {
	return m.recorder
}

// AuthenticationService mocks base method.
func (m *MockServices) AuthenticationService() AuthenticationService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticationService")
	ret0, _ := ret[0].(AuthenticationService)
	return ret0
}

// AuthenticationService indicates an expected call of AuthenticationService.
func (mr *MockServicesMockRecorder) AuthenticationService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticationService", reflect.TypeOf((*MockServices)(nil).AuthenticationService))
}

// EmailVerificationService mocks base method.
func (m *MockServices) EmailVerificationService() EmailVerificationService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailVerificationService")
	ret0, _ := ret[0].(EmailVerificationService)
	return ret0
}

// EmailVerificationService indicates an expected call of EmailVerificationService.
func (mr *MockServicesMockRecorder) EmailVerificationService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailVerificationService", reflect.TypeOf((*MockServices)(nil).EmailVerificationService))
}
