// Code generated by MockGen. DO NOT EDIT.
// Source: ledger_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=ledger_service_mock.go -source=ledger_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/ledger/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerService is a mock of LedgerService interface.
type MockLedgerService struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerServiceMockRecorder
	isgomock struct{}
}

// MockLedgerServiceMockRecorder is the mock recorder for MockLedgerService.
type MockLedgerServiceMockRecorder struct {
	mock *MockLedgerService
}

// NewMockLedgerService creates a new mock instance.
func NewMockLedgerService(ctrl *gomock.Controller) *MockLedgerService {
	mock := &MockLedgerService{ctrl: ctrl}
	mock.recorder = &MockLedgerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerService) EXPECT() *MockLedgerServiceMockRecorder {
	return m.recorder
}

// RecordLedgerEvents mocks base method.
func (m *MockLedgerService) RecordLedgerEvents(ctx context.Context, command RecordLedgerEventsCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLedgerEvents", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLedgerEvents indicates an expected call of RecordLedgerEvents.
func (mr *MockLedgerServiceMockRecorder) RecordLedgerEvents(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLedgerEvents", reflect.TypeOf((*MockLedgerService)(nil).RecordLedgerEvents), ctx, command)
}

// RecordPaymentReversed mocks base method.
func (m *MockLedgerService) RecordPaymentReversed(ctx context.Context, command RecordPaymentReversedCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentReversed", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentReversed indicates an expected call of RecordPaymentReversed.
func (mr *MockLedgerServiceMockRecorder) RecordPaymentReversed(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentReversed", reflect.TypeOf((*MockLedgerService)(nil).RecordPaymentReversed), ctx, command)
}

// RecordPaymentSucceeded mocks base method.
func (m *MockLedgerService) RecordPaymentSucceeded(ctx context.Context, command RecordPaymentSucceededCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentSucceeded", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentSucceeded indicates an expected call of RecordPaymentSucceeded.
func (mr *MockLedgerServiceMockRecorder) RecordPaymentSucceeded(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentSucceeded", reflect.TypeOf((*MockLedgerService)(nil).RecordPaymentSucceeded), ctx, command)
}

// TransferToAccount mocks base method.
func (m *MockLedgerService) TransferToAccount(ctx context.Context, command TransferToAccountCommand) (*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferToAccount", ctx, command)
	ret0, _ := ret[0].(*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferToAccount indicates an expected call of TransferToAccount.
func (mr *MockLedgerServiceMockRecorder) TransferToAccount(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferToAccount", reflect.TypeOf((*MockLedgerService)(nil).TransferToAccount), ctx, command)
}
