// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=services_mock.go -source=services.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	out "wechat-clone/core/modules/ledger/application/dto/out"
	entity "wechat-clone/core/modules/ledger/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockServices is a mock of Services interface.
type MockServices struct {
	ctrl     *gomock.Controller
	recorder *MockServicesMockRecorder
	isgomock struct{}
}

// MockServicesMockRecorder is the mock recorder for MockServices.
type MockServicesMockRecorder struct {
	mock *MockServices
}

// NewMockServices creates a new mock instance.
func NewMockServices(ctrl *gomock.Controller) *MockServices {
	mock := &MockServices{ctrl: ctrl}
	mock.recorder = &MockServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServices) EXPECT() *MockServicesMockRecorder {
	return m.recorder
}

// GetAccountBalance mocks base method.
func (m *MockServices) GetAccountBalance(ctx context.Context, accountID, currency string) (*out.AccountBalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", ctx, accountID, currency)
	ret0, _ := ret[0].(*out.AccountBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockServicesMockRecorder) GetAccountBalance(ctx, accountID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockServices)(nil).GetAccountBalance), ctx, accountID, currency)
}

// GetTransaction mocks base method.
func (m *MockServices) GetTransaction(ctx context.Context, transactionID string) (*out.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, transactionID)
	ret0, _ := ret[0].(*out.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockServicesMockRecorder) GetTransaction(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockServices)(nil).GetTransaction), ctx, transactionID)
}

// ListTransactions mocks base method.
func (m *MockServices) ListTransactions(ctx context.Context, accountID, cursor, currency string, limit int) (*out.ListTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, accountID, cursor, currency, limit)
	ret0, _ := ret[0].(*out.ListTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockServicesMockRecorder) ListTransactions(ctx, accountID, cursor, currency, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockServices)(nil).ListTransactions), ctx, accountID, cursor, currency, limit)
}

// RecordLedgerEvents mocks base method.
func (m *MockServices) RecordLedgerEvents(ctx context.Context, command RecordLedgerEventsCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLedgerEvents", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLedgerEvents indicates an expected call of RecordLedgerEvents.
func (mr *MockServicesMockRecorder) RecordLedgerEvents(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLedgerEvents", reflect.TypeOf((*MockServices)(nil).RecordLedgerEvents), ctx, command)
}

// RecordPaymentReversed mocks base method.
func (m *MockServices) RecordPaymentReversed(ctx context.Context, command RecordPaymentReversedCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentReversed", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentReversed indicates an expected call of RecordPaymentReversed.
func (mr *MockServicesMockRecorder) RecordPaymentReversed(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentReversed", reflect.TypeOf((*MockServices)(nil).RecordPaymentReversed), ctx, command)
}

// RecordPaymentSucceeded mocks base method.
func (m *MockServices) RecordPaymentSucceeded(ctx context.Context, command RecordPaymentSucceededCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentSucceeded", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentSucceeded indicates an expected call of RecordPaymentSucceeded.
func (mr *MockServicesMockRecorder) RecordPaymentSucceeded(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentSucceeded", reflect.TypeOf((*MockServices)(nil).RecordPaymentSucceeded), ctx, command)
}

// TransferToAccount mocks base method.
func (m *MockServices) TransferToAccount(ctx context.Context, command TransferToAccountCommand) (*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferToAccount", ctx, command)
	ret0, _ := ret[0].(*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferToAccount indicates an expected call of TransferToAccount.
func (mr *MockServicesMockRecorder) TransferToAccount(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferToAccount", reflect.TypeOf((*MockServices)(nil).TransferToAccount), ctx, command)
}
