// Code generated by MockGen. DO NOT EDIT.
// Source: payment_provider.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=payment_provider_mock.go -source=payment_provider.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	entity "go-socket/core/modules/payment/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentProvider is a mock of PaymentProvider interface.
type MockPaymentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderMockRecorder
	isgomock struct{}
}

// MockPaymentProviderMockRecorder is the mock recorder for MockPaymentProvider.
type MockPaymentProviderMockRecorder struct {
	mock *MockPaymentProvider
}

// NewMockPaymentProvider creates a new mock instance.
func NewMockPaymentProvider(ctrl *gomock.Controller) *MockPaymentProvider {
	mock := &MockPaymentProvider{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProvider) EXPECT() *MockPaymentProviderMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentProvider) CreatePayment(ctx context.Context, intent *entity.PaymentIntent, metadata map[string]string) (*PaymentCreation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, intent, metadata)
	ret0, _ := ret[0].(*PaymentCreation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentProviderMockRecorder) CreatePayment(ctx, intent, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentProvider)(nil).CreatePayment), ctx, intent, metadata)
}

// Name mocks base method.
func (m *MockPaymentProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPaymentProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPaymentProvider)(nil).Name))
}

// ParseWebhook mocks base method.
func (m *MockPaymentProvider) ParseWebhook(ctx context.Context, payload []byte, signature string) (*PaymentWebhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseWebhook", ctx, payload, signature)
	ret0, _ := ret[0].(*PaymentWebhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseWebhook indicates an expected call of ParseWebhook.
func (mr *MockPaymentProviderMockRecorder) ParseWebhook(ctx, payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseWebhook", reflect.TypeOf((*MockPaymentProvider)(nil).ParseWebhook), ctx, payload, signature)
}

// MockPaymentProviderRegistry is a mock of PaymentProviderRegistry interface.
type MockPaymentProviderRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderRegistryMockRecorder
	isgomock struct{}
}

// MockPaymentProviderRegistryMockRecorder is the mock recorder for MockPaymentProviderRegistry.
type MockPaymentProviderRegistryMockRecorder struct {
	mock *MockPaymentProviderRegistry
}

// NewMockPaymentProviderRegistry creates a new mock instance.
func NewMockPaymentProviderRegistry(ctrl *gomock.Controller) *MockPaymentProviderRegistry {
	mock := &MockPaymentProviderRegistry{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProviderRegistry) EXPECT() *MockPaymentProviderRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPaymentProviderRegistry) Get(name string) (PaymentProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(PaymentProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPaymentProviderRegistryMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPaymentProviderRegistry)(nil).Get), name)
}
