// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/notification/domain/repos/notification_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/notification/domain/repos/notification_repo_mock.go -source=core/modules/notification/domain/repos/notification_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	aggregate "wechat-clone/core/modules/notification/domain/aggregate"
	entity "wechat-clone/core/modules/notification/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// CountUnread mocks base method.
func (m *MockNotificationRepository) CountUnread(ctx context.Context, accountID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnread", ctx, accountID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnread indicates an expected call of CountUnread.
func (mr *MockNotificationRepositoryMockRecorder) CountUnread(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnread", reflect.TypeOf((*MockNotificationRepository)(nil).CountUnread), ctx, accountID)
}

// ListByAccountID mocks base method.
func (m *MockNotificationRepository) ListByAccountID(ctx context.Context, accountID string, cursor *NotificationListCursor, limit int) ([]*entity.NotificationEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountID", ctx, accountID, cursor, limit)
	ret0, _ := ret[0].([]*entity.NotificationEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountID indicates an expected call of ListByAccountID.
func (mr *MockNotificationRepositoryMockRecorder) ListByAccountID(ctx, accountID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountID", reflect.TypeOf((*MockNotificationRepository)(nil).ListByAccountID), ctx, accountID, cursor, limit)
}

// ListUnreadByAccountID mocks base method.
func (m *MockNotificationRepository) ListUnreadByAccountID(ctx context.Context, accountID string, limit int) ([]*entity.NotificationEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnreadByAccountID", ctx, accountID, limit)
	ret0, _ := ret[0].([]*entity.NotificationEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnreadByAccountID indicates an expected call of ListUnreadByAccountID.
func (mr *MockNotificationRepositoryMockRecorder) ListUnreadByAccountID(ctx, accountID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnreadByAccountID", reflect.TypeOf((*MockNotificationRepository)(nil).ListUnreadByAccountID), ctx, accountID, limit)
}

// Load mocks base method.
func (m *MockNotificationRepository) Load(ctx context.Context, notificationID string) (*aggregate.NotificationAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, notificationID)
	ret0, _ := ret[0].(*aggregate.NotificationAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockNotificationRepositoryMockRecorder) Load(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockNotificationRepository)(nil).Load), ctx, notificationID)
}

// LoadMessageGroup mocks base method.
func (m *MockNotificationRepository) LoadMessageGroup(ctx context.Context, accountID, groupKey string) (*aggregate.NotificationAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadMessageGroup", ctx, accountID, groupKey)
	ret0, _ := ret[0].(*aggregate.NotificationAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadMessageGroup indicates an expected call of LoadMessageGroup.
func (mr *MockNotificationRepositoryMockRecorder) LoadMessageGroup(ctx, accountID, groupKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadMessageGroup", reflect.TypeOf((*MockNotificationRepository)(nil).LoadMessageGroup), ctx, accountID, groupKey)
}

// Save mocks base method.
func (m *MockNotificationRepository) Save(ctx context.Context, notification *aggregate.NotificationAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockNotificationRepositoryMockRecorder) Save(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNotificationRepository)(nil).Save), ctx, notification)
}
