// Code generated by MockGen. DO NOT EDIT.
// Source: push_subscription_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=push_subscription_repo_mock.go -source=push_subscription_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/notification/domain/aggregate"
	entity "go-socket/core/modules/notification/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPushSubscriptionRepository is a mock of PushSubscriptionRepository interface.
type MockPushSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionRepositoryMockRecorder is the mock recorder for MockPushSubscriptionRepository.
type MockPushSubscriptionRepositoryMockRecorder struct {
	mock *MockPushSubscriptionRepository
}

// NewMockPushSubscriptionRepository creates a new mock instance.
func NewMockPushSubscriptionRepository(ctrl *gomock.Controller) *MockPushSubscriptionRepository {
	mock := &MockPushSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionRepository) EXPECT() *MockPushSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// ListPushSubscriptionsByAccountID mocks base method.
func (m *MockPushSubscriptionRepository) ListPushSubscriptionsByAccountID(ctx context.Context, accountID string) ([]*entity.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPushSubscriptionsByAccountID", ctx, accountID)
	ret0, _ := ret[0].([]*entity.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPushSubscriptionsByAccountID indicates an expected call of ListPushSubscriptionsByAccountID.
func (mr *MockPushSubscriptionRepositoryMockRecorder) ListPushSubscriptionsByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPushSubscriptionsByAccountID", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).ListPushSubscriptionsByAccountID), ctx, accountID)
}

// LoadByAccountAndEndpoint mocks base method.
func (m *MockPushSubscriptionRepository) LoadByAccountAndEndpoint(ctx context.Context, accountID, endpoint string) (*aggregate.PushSubscriptionAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByAccountAndEndpoint", ctx, accountID, endpoint)
	ret0, _ := ret[0].(*aggregate.PushSubscriptionAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByAccountAndEndpoint indicates an expected call of LoadByAccountAndEndpoint.
func (mr *MockPushSubscriptionRepositoryMockRecorder) LoadByAccountAndEndpoint(ctx, accountID, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByAccountAndEndpoint", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).LoadByAccountAndEndpoint), ctx, accountID, endpoint)
}

// Save mocks base method.
func (m *MockPushSubscriptionRepository) Save(ctx context.Context, subscription *aggregate.PushSubscriptionAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPushSubscriptionRepositoryMockRecorder) Save(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPushSubscriptionRepository)(nil).Save), ctx, subscription)
}
