// Code generated by MockGen. DO NOT EDIT.
// Source: repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=repos_mock.go -source=repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// NotificationRepository mocks base method.
func (m *MockRepos) NotificationRepository() NotificationRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotificationRepository")
	ret0, _ := ret[0].(NotificationRepository)
	return ret0
}

// NotificationRepository indicates an expected call of NotificationRepository.
func (mr *MockReposMockRecorder) NotificationRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotificationRepository", reflect.TypeOf((*MockRepos)(nil).NotificationRepository))
}

// PushSubscriptionRepository mocks base method.
func (m *MockRepos) PushSubscriptionRepository() PushSubscriptionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushSubscriptionRepository")
	ret0, _ := ret[0].(PushSubscriptionRepository)
	return ret0
}

// PushSubscriptionRepository indicates an expected call of PushSubscriptionRepository.
func (mr *MockReposMockRecorder) PushSubscriptionRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushSubscriptionRepository", reflect.TypeOf((*MockRepos)(nil).PushSubscriptionRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
