// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -package=projection -destination=contracts_mock.go -source=contracts.go
//

// Package projection is a generated GoMock package.
package projection

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServingProjector is a mock of ServingProjector interface.
type MockServingProjector struct {
	ctrl     *gomock.Controller
	recorder *MockServingProjectorMockRecorder
	isgomock struct{}
}

// MockServingProjectorMockRecorder is the mock recorder for MockServingProjector.
type MockServingProjectorMockRecorder struct {
	mock *MockServingProjector
}

// NewMockServingProjector creates a new mock instance.
func NewMockServingProjector(ctrl *gomock.Controller) *MockServingProjector {
	mock := &MockServingProjector{ctrl: ctrl}
	mock.recorder = &MockServingProjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServingProjector) EXPECT() *MockServingProjectorMockRecorder {
	return m.recorder
}

// DeleteRoomAggregate mocks base method.
func (m *MockServingProjector) DeleteRoomAggregate(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoomAggregate", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoomAggregate indicates an expected call of DeleteRoomAggregate.
func (mr *MockServingProjectorMockRecorder) DeleteRoomAggregate(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoomAggregate", reflect.TypeOf((*MockServingProjector)(nil).DeleteRoomAggregate), ctx, roomID)
}

// SyncMessageAggregate mocks base method.
func (m *MockServingProjector) SyncMessageAggregate(ctx context.Context, projection *MessageAggregateSync) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMessageAggregate", ctx, projection)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMessageAggregate indicates an expected call of SyncMessageAggregate.
func (mr *MockServingProjectorMockRecorder) SyncMessageAggregate(ctx, projection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMessageAggregate", reflect.TypeOf((*MockServingProjector)(nil).SyncMessageAggregate), ctx, projection)
}

// SyncRoomAggregate mocks base method.
func (m *MockServingProjector) SyncRoomAggregate(ctx context.Context, projection *RoomAggregateSync) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncRoomAggregate", ctx, projection)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncRoomAggregate indicates an expected call of SyncRoomAggregate.
func (mr *MockServingProjectorMockRecorder) SyncRoomAggregate(ctx, projection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncRoomAggregate", reflect.TypeOf((*MockServingProjector)(nil).SyncRoomAggregate), ctx, projection)
}

// MockMessageSearchIndexer is a mock of MessageSearchIndexer interface.
type MockMessageSearchIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSearchIndexerMockRecorder
	isgomock struct{}
}

// MockMessageSearchIndexerMockRecorder is the mock recorder for MockMessageSearchIndexer.
type MockMessageSearchIndexerMockRecorder struct {
	mock *MockMessageSearchIndexer
}

// NewMockMessageSearchIndexer creates a new mock instance.
func NewMockMessageSearchIndexer(ctrl *gomock.Controller) *MockMessageSearchIndexer {
	mock := &MockMessageSearchIndexer{ctrl: ctrl}
	mock.recorder = &MockMessageSearchIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSearchIndexer) EXPECT() *MockMessageSearchIndexerMockRecorder {
	return m.recorder
}

// DeleteRoom mocks base method.
func (m *MockMessageSearchIndexer) DeleteRoom(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockMessageSearchIndexerMockRecorder) DeleteRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockMessageSearchIndexer)(nil).DeleteRoom), ctx, roomID)
}

// SyncMessage mocks base method.
func (m *MockMessageSearchIndexer) SyncMessage(ctx context.Context, message *MessageProjection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMessage indicates an expected call of SyncMessage.
func (mr *MockMessageSearchIndexerMockRecorder) SyncMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMessage", reflect.TypeOf((*MockMessageSearchIndexer)(nil).SyncMessage), ctx, message)
}
