// Code generated by MockGen. DO NOT EDIT.
// Source: query_repos.go
//
// Generated by this command:
//
//	mockgen -package=projection -destination=query_repos_mock.go -source=query_repos.go
//

// Package projection is a generated GoMock package.
package projection

import (
	context "context"
	views "go-socket/core/modules/room/infra/projection/cassandra/views"
	utils "go-socket/core/shared/utils"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockQueryRepos is a mock of QueryRepos interface.
type MockQueryRepos struct {
	ctrl     *gomock.Controller
	recorder *MockQueryReposMockRecorder
	isgomock struct{}
}

// MockQueryReposMockRecorder is the mock recorder for MockQueryRepos.
type MockQueryReposMockRecorder struct {
	mock *MockQueryRepos
}

// NewMockQueryRepos creates a new mock instance.
func NewMockQueryRepos(ctrl *gomock.Controller) *MockQueryRepos {
	mock := &MockQueryRepos{ctrl: ctrl}
	mock.recorder = &MockQueryReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepos) EXPECT() *MockQueryReposMockRecorder {
	return m.recorder
}

// MessageReadRepository mocks base method.
func (m *MockQueryRepos) MessageReadRepository() MessageReadRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageReadRepository")
	ret0, _ := ret[0].(MessageReadRepository)
	return ret0
}

// MessageReadRepository indicates an expected call of MessageReadRepository.
func (mr *MockQueryReposMockRecorder) MessageReadRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageReadRepository", reflect.TypeOf((*MockQueryRepos)(nil).MessageReadRepository))
}

// RoomMemberReadRepository mocks base method.
func (m *MockQueryRepos) RoomMemberReadRepository() RoomMemberReadRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomMemberReadRepository")
	ret0, _ := ret[0].(RoomMemberReadRepository)
	return ret0
}

// RoomMemberReadRepository indicates an expected call of RoomMemberReadRepository.
func (mr *MockQueryReposMockRecorder) RoomMemberReadRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomMemberReadRepository", reflect.TypeOf((*MockQueryRepos)(nil).RoomMemberReadRepository))
}

// RoomReadRepository mocks base method.
func (m *MockQueryRepos) RoomReadRepository() RoomReadRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomReadRepository")
	ret0, _ := ret[0].(RoomReadRepository)
	return ret0
}

// RoomReadRepository indicates an expected call of RoomReadRepository.
func (mr *MockQueryReposMockRecorder) RoomReadRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomReadRepository", reflect.TypeOf((*MockQueryRepos)(nil).RoomReadRepository))
}

// MockRoomReadRepository is a mock of RoomReadRepository interface.
type MockRoomReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomReadRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomReadRepositoryMockRecorder is the mock recorder for MockRoomReadRepository.
type MockRoomReadRepositoryMockRecorder struct {
	mock *MockRoomReadRepository
}

// NewMockRoomReadRepository creates a new mock instance.
func NewMockRoomReadRepository(ctrl *gomock.Controller) *MockRoomReadRepository {
	mock := &MockRoomReadRepository{ctrl: ctrl}
	mock.recorder = &MockRoomReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomReadRepository) EXPECT() *MockRoomReadRepositoryMockRecorder {
	return m.recorder
}

// GetRoomByID mocks base method.
func (m *MockRoomReadRepository) GetRoomByID(ctx context.Context, id string) (*views.RoomView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", ctx, id)
	ret0, _ := ret[0].(*views.RoomView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockRoomReadRepositoryMockRecorder) GetRoomByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockRoomReadRepository)(nil).GetRoomByID), ctx, id)
}

// ListRooms mocks base method.
func (m *MockRoomReadRepository) ListRooms(ctx context.Context, options utils.QueryOptions) ([]*views.RoomView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx, options)
	ret0, _ := ret[0].([]*views.RoomView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRoomReadRepositoryMockRecorder) ListRooms(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRoomReadRepository)(nil).ListRooms), ctx, options)
}

// ListRoomsByAccount mocks base method.
func (m *MockRoomReadRepository) ListRoomsByAccount(ctx context.Context, accountID string, options utils.QueryOptions) ([]*views.RoomView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsByAccount", ctx, accountID, options)
	ret0, _ := ret[0].([]*views.RoomView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsByAccount indicates an expected call of ListRoomsByAccount.
func (mr *MockRoomReadRepositoryMockRecorder) ListRoomsByAccount(ctx, accountID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsByAccount", reflect.TypeOf((*MockRoomReadRepository)(nil).ListRoomsByAccount), ctx, accountID, options)
}

// MockMessageReadRepository is a mock of MessageReadRepository interface.
type MockMessageReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageReadRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageReadRepositoryMockRecorder is the mock recorder for MockMessageReadRepository.
type MockMessageReadRepositoryMockRecorder struct {
	mock *MockMessageReadRepository
}

// NewMockMessageReadRepository creates a new mock instance.
func NewMockMessageReadRepository(ctrl *gomock.Controller) *MockMessageReadRepository {
	mock := &MockMessageReadRepository{ctrl: ctrl}
	mock.recorder = &MockMessageReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageReadRepository) EXPECT() *MockMessageReadRepositoryMockRecorder {
	return m.recorder
}

// CountMessageReceiptsByStatus mocks base method.
func (m *MockMessageReadRepository) CountMessageReceiptsByStatus(ctx context.Context, messageID, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMessageReceiptsByStatus", ctx, messageID, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMessageReceiptsByStatus indicates an expected call of CountMessageReceiptsByStatus.
func (mr *MockMessageReadRepositoryMockRecorder) CountMessageReceiptsByStatus(ctx, messageID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMessageReceiptsByStatus", reflect.TypeOf((*MockMessageReadRepository)(nil).CountMessageReceiptsByStatus), ctx, messageID, status)
}

// CountUnreadMessages mocks base method.
func (m *MockMessageReadRepository) CountUnreadMessages(ctx context.Context, roomID, accountID string, lastReadAt *time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadMessages", ctx, roomID, accountID, lastReadAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadMessages indicates an expected call of CountUnreadMessages.
func (mr *MockMessageReadRepositoryMockRecorder) CountUnreadMessages(ctx, roomID, accountID, lastReadAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadMessages", reflect.TypeOf((*MockMessageReadRepository)(nil).CountUnreadMessages), ctx, roomID, accountID, lastReadAt)
}

// GetLastMessage mocks base method.
func (m *MockMessageReadRepository) GetLastMessage(ctx context.Context, roomID string) (*views.MessageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMessage", ctx, roomID)
	ret0, _ := ret[0].(*views.MessageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMessage indicates an expected call of GetLastMessage.
func (mr *MockMessageReadRepositoryMockRecorder) GetLastMessage(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMessage", reflect.TypeOf((*MockMessageReadRepository)(nil).GetLastMessage), ctx, roomID)
}

// GetMessageByID mocks base method.
func (m *MockMessageReadRepository) GetMessageByID(ctx context.Context, id string) (*views.MessageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, id)
	ret0, _ := ret[0].(*views.MessageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageReadRepositoryMockRecorder) GetMessageByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageReadRepository)(nil).GetMessageByID), ctx, id)
}

// GetMessageReceipt mocks base method.
func (m *MockMessageReadRepository) GetMessageReceipt(ctx context.Context, lookup MessageReceiptLookup) (*MessageReceiptStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageReceipt", ctx, lookup)
	ret0, _ := ret[0].(*MessageReceiptStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageReceipt indicates an expected call of GetMessageReceipt.
func (mr *MockMessageReadRepositoryMockRecorder) GetMessageReceipt(ctx, lookup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageReceipt", reflect.TypeOf((*MockMessageReadRepository)(nil).GetMessageReceipt), ctx, lookup)
}

// ListMessages mocks base method.
func (m *MockMessageReadRepository) ListMessages(ctx context.Context, accountID, roomID string, options MessageListOptions) ([]*views.MessageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, accountID, roomID, options)
	ret0, _ := ret[0].([]*views.MessageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockMessageReadRepositoryMockRecorder) ListMessages(ctx, accountID, roomID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockMessageReadRepository)(nil).ListMessages), ctx, accountID, roomID, options)
}

// MockRoomMemberReadRepository is a mock of RoomMemberReadRepository interface.
type MockRoomMemberReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMemberReadRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomMemberReadRepositoryMockRecorder is the mock recorder for MockRoomMemberReadRepository.
type MockRoomMemberReadRepositoryMockRecorder struct {
	mock *MockRoomMemberReadRepository
}

// NewMockRoomMemberReadRepository creates a new mock instance.
func NewMockRoomMemberReadRepository(ctrl *gomock.Controller) *MockRoomMemberReadRepository {
	mock := &MockRoomMemberReadRepository{ctrl: ctrl}
	mock.recorder = &MockRoomMemberReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMemberReadRepository) EXPECT() *MockRoomMemberReadRepositoryMockRecorder {
	return m.recorder
}

// GetRoomMemberByAccount mocks base method.
func (m *MockRoomMemberReadRepository) GetRoomMemberByAccount(ctx context.Context, roomID, accountID string) (*views.RoomMemberView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMemberByAccount", ctx, roomID, accountID)
	ret0, _ := ret[0].(*views.RoomMemberView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomMemberByAccount indicates an expected call of GetRoomMemberByAccount.
func (mr *MockRoomMemberReadRepositoryMockRecorder) GetRoomMemberByAccount(ctx, roomID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMemberByAccount", reflect.TypeOf((*MockRoomMemberReadRepository)(nil).GetRoomMemberByAccount), ctx, roomID, accountID)
}

// ListRoomMembers mocks base method.
func (m *MockRoomMemberReadRepository) ListRoomMembers(ctx context.Context, roomID string) ([]*views.RoomMemberView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomMembers", ctx, roomID)
	ret0, _ := ret[0].([]*views.RoomMemberView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomMembers indicates an expected call of ListRoomMembers.
func (mr *MockRoomMemberReadRepositoryMockRecorder) ListRoomMembers(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomMembers", reflect.TypeOf((*MockRoomMemberReadRepository)(nil).ListRoomMembers), ctx, roomID)
}

// SearchMentionCandidates mocks base method.
func (m *MockRoomMemberReadRepository) SearchMentionCandidates(ctx context.Context, search MentionCandidateSearch) ([]*views.MentionCandidateView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMentionCandidates", ctx, search)
	ret0, _ := ret[0].([]*views.MentionCandidateView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMentionCandidates indicates an expected call of SearchMentionCandidates.
func (mr *MockRoomMemberReadRepositoryMockRecorder) SearchMentionCandidates(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMentionCandidates", reflect.TypeOf((*MockRoomMemberReadRepository)(nil).SearchMentionCandidates), ctx, search)
}
