// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/notification/application/service/realtime_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=core/modules/notification/application/service/realtime_service_mock.go -source=core/modules/notification/application/service/realtime_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	types "wechat-clone/core/modules/notification/types"

	gomock "go.uber.org/mock/gomock"
)

// MockRealtimeService is a mock of RealtimeService interface.
type MockRealtimeService struct {
	ctrl     *gomock.Controller
	recorder *MockRealtimeServiceMockRecorder
	isgomock struct{}
}

// MockRealtimeServiceMockRecorder is the mock recorder for MockRealtimeService.
type MockRealtimeServiceMockRecorder struct {
	mock *MockRealtimeService
}

// NewMockRealtimeService creates a new mock instance.
func NewMockRealtimeService(ctrl *gomock.Controller) *MockRealtimeService {
	mock := &MockRealtimeService{ctrl: ctrl}
	mock.recorder = &MockRealtimeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealtimeService) EXPECT() *MockRealtimeServiceMockRecorder {
	return m.recorder
}

// EmitMessage mocks base method.
func (m *MockRealtimeService) EmitMessage(ctx context.Context, message types.RealtimeMessagePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitMessage indicates an expected call of EmitMessage.
func (mr *MockRealtimeServiceMockRecorder) EmitMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitMessage", reflect.TypeOf((*MockRealtimeService)(nil).EmitMessage), ctx, message)
}
