// Code generated by MockGen. DO NOT EDIT.
// Source: email_sender.go
//
// Generated by this command:
//
//	mockgen -package=adapter -destination=email_sender_mock.go -source=email_sender.go
//

// Package adapter is a generated GoMock package.
package adapter

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendTemplate mocks base method.
func (m *MockEmailSender) SendTemplate(ctx context.Context, to, subject, templateName string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplate", ctx, to, subject, templateName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTemplate indicates an expected call of SendTemplate.
func (mr *MockEmailSenderMockRecorder) SendTemplate(ctx, to, subject, templateName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplate", reflect.TypeOf((*MockEmailSender)(nil).SendTemplate), ctx, to, subject, templateName, data)
}
