// Code generated by MockGen. DO NOT EDIT.
// Source: migrate.go
//
// Generated by this command:
//
//	mockgen -package=cassandra -destination=migrate_mock.go -source=migrate.go
//

// Package cassandra is a generated GoMock package.
package cassandra

import (
	context "context"
	reflect "reflect"

	gocql "github.com/gocql/gocql"
	gomock "go.uber.org/mock/gomock"
)

// MockMigrateTool is a mock of MigrateTool interface.
type MockMigrateTool struct {
	ctrl     *gomock.Controller
	recorder *MockMigrateToolMockRecorder
	isgomock struct{}
}

// MockMigrateToolMockRecorder is the mock recorder for MockMigrateTool.
type MockMigrateToolMockRecorder struct {
	mock *MockMigrateTool
}

// NewMockMigrateTool creates a new mock instance.
func NewMockMigrateTool(ctrl *gomock.Controller) *MockMigrateTool {
	mock := &MockMigrateTool{ctrl: ctrl}
	mock.recorder = &MockMigrateToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrateTool) EXPECT() *MockMigrateToolMockRecorder {
	return m.recorder
}

// Migrate mocks base method.
func (m *MockMigrateTool) Migrate(ctx context.Context, session *gocql.Session, migrationTable string, migrations []Migration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, session, migrationTable, migrations)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockMigrateToolMockRecorder) Migrate(ctx, session, migrationTable, migrations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockMigrateTool)(nil).Migrate), ctx, session, migrationTable, migrations)
}

// MigrateFromSource mocks base method.
func (m *MockMigrateTool) MigrateFromSource(ctx context.Context, session *gocql.Session, migrationTable, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateFromSource", ctx, session, migrationTable, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateFromSource indicates an expected call of MigrateFromSource.
func (mr *MockMigrateToolMockRecorder) MigrateFromSource(ctx, session, migrationTable, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateFromSource", reflect.TypeOf((*MockMigrateTool)(nil).MigrateFromSource), ctx, session, migrationTable, source)
}
