// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/ledger/domain/repos/ledger_account_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/ledger/domain/repos/ledger_account_aggregate_repo_mock.go -source=core/modules/ledger/domain/repos/ledger_account_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	aggregate "wechat-clone/core/modules/ledger/domain/aggregate"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerAccountAggregateRepository is a mock of LedgerAccountAggregateRepository interface.
type MockLedgerAccountAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerAccountAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerAccountAggregateRepositoryMockRecorder is the mock recorder for MockLedgerAccountAggregateRepository.
type MockLedgerAccountAggregateRepositoryMockRecorder struct {
	mock *MockLedgerAccountAggregateRepository
}

// NewMockLedgerAccountAggregateRepository creates a new mock instance.
func NewMockLedgerAccountAggregateRepository(ctrl *gomock.Controller) *MockLedgerAccountAggregateRepository {
	mock := &MockLedgerAccountAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerAccountAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerAccountAggregateRepository) EXPECT() *MockLedgerAccountAggregateRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockLedgerAccountAggregateRepository) Load(ctx context.Context, accountID string) (*aggregate.LedgerAccountAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, accountID)
	ret0, _ := ret[0].(*aggregate.LedgerAccountAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockLedgerAccountAggregateRepositoryMockRecorder) Load(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockLedgerAccountAggregateRepository)(nil).Load), ctx, accountID)
}

// Save mocks base method.
func (m *MockLedgerAccountAggregateRepository) Save(ctx context.Context, arg1 *aggregate.LedgerAccountAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLedgerAccountAggregateRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLedgerAccountAggregateRepository)(nil).Save), ctx, arg1)
}
