// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/ledger/domain/repos/ledger_outbox_events_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/ledger/domain/repos/ledger_outbox_events_repo_mock.go -source=core/modules/ledger/domain/repos/ledger_outbox_events_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	event "go-socket/core/shared/pkg/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerOutboxEventsRepository is a mock of LedgerOutboxEventsRepository interface.
type MockLedgerOutboxEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerOutboxEventsRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerOutboxEventsRepositoryMockRecorder is the mock recorder for MockLedgerOutboxEventsRepository.
type MockLedgerOutboxEventsRepositoryMockRecorder struct {
	mock *MockLedgerOutboxEventsRepository
}

// NewMockLedgerOutboxEventsRepository creates a new mock instance.
func NewMockLedgerOutboxEventsRepository(ctrl *gomock.Controller) *MockLedgerOutboxEventsRepository {
	mock := &MockLedgerOutboxEventsRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerOutboxEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerOutboxEventsRepository) EXPECT() *MockLedgerOutboxEventsRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockLedgerOutboxEventsRepository) Append(ctx context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockLedgerOutboxEventsRepositoryMockRecorder) Append(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockLedgerOutboxEventsRepository)(nil).Append), ctx, arg1)
}
