// Code generated by MockGen. DO NOT EDIT.
// Source: ledger_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=ledger_repo_mock.go -source=ledger_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/ledger/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerRepository is a mock of LedgerRepository interface.
type MockLedgerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerRepositoryMockRecorder is the mock recorder for MockLedgerRepository.
type MockLedgerRepositoryMockRecorder struct {
	mock *MockLedgerRepository
}

// NewMockLedgerRepository creates a new mock instance.
func NewMockLedgerRepository(ctrl *gomock.Controller) *MockLedgerRepository {
	mock := &MockLedgerRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerRepository) EXPECT() *MockLedgerRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockLedgerRepository) CreateTransaction(ctx context.Context, transaction *entity.LedgerTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockLedgerRepositoryMockRecorder) CreateTransaction(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockLedgerRepository)(nil).CreateTransaction), ctx, transaction)
}

// GetBalance mocks base method.
func (m *MockLedgerRepository) GetBalance(ctx context.Context, accountID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockLedgerRepositoryMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockLedgerRepository)(nil).GetBalance), ctx, accountID)
}

// GetTransaction mocks base method.
func (m *MockLedgerRepository) GetTransaction(ctx context.Context, transactionID string) (*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, transactionID)
	ret0, _ := ret[0].(*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockLedgerRepositoryMockRecorder) GetTransaction(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockLedgerRepository)(nil).GetTransaction), ctx, transactionID)
}

// InsertEntries mocks base method.
func (m *MockLedgerRepository) InsertEntries(ctx context.Context, entries []*entity.LedgerEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEntries", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEntries indicates an expected call of InsertEntries.
func (mr *MockLedgerRepositoryMockRecorder) InsertEntries(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEntries", reflect.TypeOf((*MockLedgerRepository)(nil).InsertEntries), ctx, entries)
}
