// Code generated by MockGen. DO NOT EDIT.
// Source: payment_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=payment_repo_mock.go -source=payment_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	entity "go-socket/core/modules/ledger/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// CreateIntent mocks base method.
func (m *MockPaymentRepository) CreateIntent(ctx context.Context, intent *entity.PaymentIntent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIntent", ctx, intent)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIntent indicates an expected call of CreateIntent.
func (mr *MockPaymentRepositoryMockRecorder) CreateIntent(ctx, intent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIntent", reflect.TypeOf((*MockPaymentRepository)(nil).CreateIntent), ctx, intent)
}

// GetIntentByExternalRef mocks base method.
func (m *MockPaymentRepository) GetIntentByExternalRef(ctx context.Context, provider, externalRef string) (*entity.PaymentIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntentByExternalRef", ctx, provider, externalRef)
	ret0, _ := ret[0].(*entity.PaymentIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntentByExternalRef indicates an expected call of GetIntentByExternalRef.
func (mr *MockPaymentRepositoryMockRecorder) GetIntentByExternalRef(ctx, provider, externalRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntentByExternalRef", reflect.TypeOf((*MockPaymentRepository)(nil).GetIntentByExternalRef), ctx, provider, externalRef)
}

// GetIntentByTransactionID mocks base method.
func (m *MockPaymentRepository) GetIntentByTransactionID(ctx context.Context, transactionID string) (*entity.PaymentIntent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntentByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*entity.PaymentIntent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntentByTransactionID indicates an expected call of GetIntentByTransactionID.
func (mr *MockPaymentRepositoryMockRecorder) GetIntentByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntentByTransactionID", reflect.TypeOf((*MockPaymentRepository)(nil).GetIntentByTransactionID), ctx, transactionID)
}

// IsProcessed mocks base method.
func (m *MockPaymentRepository) IsProcessed(ctx context.Context, provider, idempotencyKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessed", ctx, provider, idempotencyKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProcessed indicates an expected call of IsProcessed.
func (mr *MockPaymentRepositoryMockRecorder) IsProcessed(ctx, provider, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessed", reflect.TypeOf((*MockPaymentRepository)(nil).IsProcessed), ctx, provider, idempotencyKey)
}

// MarkProcessed mocks base method.
func (m *MockPaymentRepository) MarkProcessed(ctx context.Context, event *entity.ProcessedPaymentEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockPaymentRepositoryMockRecorder) MarkProcessed(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockPaymentRepository)(nil).MarkProcessed), ctx, event)
}

// UpdateIntentProviderState mocks base method.
func (m *MockPaymentRepository) UpdateIntentProviderState(ctx context.Context, transactionID, externalRef, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIntentProviderState", ctx, transactionID, externalRef, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIntentProviderState indicates an expected call of UpdateIntentProviderState.
func (mr *MockPaymentRepositoryMockRecorder) UpdateIntentProviderState(ctx, transactionID, externalRef, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIntentProviderState", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateIntentProviderState), ctx, transactionID, externalRef, status)
}

// UpdateIntentStatus mocks base method.
func (m *MockPaymentRepository) UpdateIntentStatus(ctx context.Context, transactionID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIntentStatus", ctx, transactionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIntentStatus indicates an expected call of UpdateIntentStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdateIntentStatus(ctx, transactionID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIntentStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateIntentStatus), ctx, transactionID, status)
}
