// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/ledger/domain/repos/repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/ledger/domain/repos/repos_mock.go -source=core/modules/ledger/domain/repos/repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// LedgerAccountAggregateRepository mocks base method.
func (m *MockRepos) LedgerAccountAggregateRepository() LedgerAccountAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LedgerAccountAggregateRepository")
	ret0, _ := ret[0].(LedgerAccountAggregateRepository)
	return ret0
}

// LedgerAccountAggregateRepository indicates an expected call of LedgerAccountAggregateRepository.
func (mr *MockReposMockRecorder) LedgerAccountAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LedgerAccountAggregateRepository", reflect.TypeOf((*MockRepos)(nil).LedgerAccountAggregateRepository))
}

// LedgerOutboxEventsRepository mocks base method.
func (m *MockRepos) LedgerOutboxEventsRepository() LedgerOutboxEventsRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LedgerOutboxEventsRepository")
	ret0, _ := ret[0].(LedgerOutboxEventsRepository)
	return ret0
}

// LedgerOutboxEventsRepository indicates an expected call of LedgerOutboxEventsRepository.
func (mr *MockReposMockRecorder) LedgerOutboxEventsRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LedgerOutboxEventsRepository", reflect.TypeOf((*MockRepos)(nil).LedgerOutboxEventsRepository))
}

// LedgerRepository mocks base method.
func (m *MockRepos) LedgerRepository() LedgerRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LedgerRepository")
	ret0, _ := ret[0].(LedgerRepository)
	return ret0
}

// LedgerRepository indicates an expected call of LedgerRepository.
func (mr *MockReposMockRecorder) LedgerRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LedgerRepository", reflect.TypeOf((*MockRepos)(nil).LedgerRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
