// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=services_mock.go -source=services.go
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServices is a mock of Services interface.
type MockServices struct {
	ctrl     *gomock.Controller
	recorder *MockServicesMockRecorder
	isgomock struct{}
}

// MockServicesMockRecorder is the mock recorder for MockServices.
type MockServicesMockRecorder struct {
	mock *MockServices
}

// NewMockServices creates a new mock instance.
func NewMockServices(ctrl *gomock.Controller) *MockServices {
	mock := &MockServices{ctrl: ctrl}
	mock.recorder = &MockServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServices) EXPECT() *MockServicesMockRecorder {
	return m.recorder
}

// PaymentCommandService mocks base method.
func (m *MockServices) PaymentCommandService() PaymentCommandService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentCommandService")
	ret0, _ := ret[0].(PaymentCommandService)
	return ret0
}

// PaymentCommandService indicates an expected call of PaymentCommandService.
func (mr *MockServicesMockRecorder) PaymentCommandService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentCommandService", reflect.TypeOf((*MockServices)(nil).PaymentCommandService))
}
