SET DEFINE OFF;

ALTER SESSION SET CONTAINER = CDB$ROOT;

DECLARE
  dbzuser_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO dbzuser_count
  FROM cdb_users
  WHERE username = 'C##DBZUSER';

  IF dbzuser_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER C##DBZUSER IDENTIFIED BY "Dbz123" CONTAINER=ALL';
  END IF;

  EXECUTE IMMEDIATE 'ALTER USER C##DBZUSER IDENTIFIED BY "Dbz123" ACCOUNT UNLOCK';
END;
/

GRANT CREATE SESSION TO C##DBZUSER CONTAINER=ALL;
GRANT SET CONTAINER TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##DBZUSER CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##DBZUSER CONTAINER=ALL;
GRANT LOGMINING TO C##DBZUSER CONTAINER=ALL;
GRANT CREATE TABLE TO C##DBZUSER CONTAINER=ALL;
GRANT CREATE SEQUENCE TO C##DBZUSER CONTAINER=ALL;

GRANT SELECT ON V_$DATABASE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_SESSION TO C##DBZUSER CONTAINER=ALL;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  appuser_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO appuser_count
  FROM dba_users
  WHERE username = 'APPUSER';

  IF appuser_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER appuser IDENTIFIED BY "App123"';
  END IF;

  EXECUTE IMMEDIATE 'ALTER USER appuser IDENTIFIED BY "App123" ACCOUNT UNLOCK';
END;
/

GRANT CREATE SESSION TO appuser;
GRANT CONNECT TO appuser;
GRANT RESOURCE TO appuser;
ALTER USER appuser QUOTA UNLIMITED ON USERS;

ALTER USER C##DBZUSER QUOTA UNLIMITED ON USERS;


BEGIN
  EXECUTE IMMEDIATE 'GRANT SELECT ON APPUSER.ACCOUNT_OUTBOX_EVENTS TO C##DBZUSER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT SELECT ON APPUSER.ROOM_OUTBOX_EVENTS TO C##DBZUSER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT SELECT ON APPUSER.PAYMENT_EVENTS TO C##DBZUSER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE APPUSER.ACCOUNT_OUTBOX_EVENTS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE APPUSER.ROOM_OUTBOX_EVENTS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE APPUSER.PAYMENT_EVENTS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
