// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/notification/application/query/notification_read_repository.go
//
// Generated by this command:
//
//	mockgen -package=query -destination=core/modules/notification/application/query/notification_read_repository_mock.go -source=core/modules/notification/application/query/notification_read_repository.go
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/notification/domain/entity"
	repos "wechat-clone/core/modules/notification/domain/repos"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationReadRepository is a mock of NotificationReadRepository interface.
type MockNotificationReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationReadRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationReadRepositoryMockRecorder is the mock recorder for MockNotificationReadRepository.
type MockNotificationReadRepositoryMockRecorder struct {
	mock *MockNotificationReadRepository
}

// NewMockNotificationReadRepository creates a new mock instance.
func NewMockNotificationReadRepository(ctrl *gomock.Controller) *MockNotificationReadRepository {
	mock := &MockNotificationReadRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationReadRepository) EXPECT() *MockNotificationReadRepositoryMockRecorder {
	return m.recorder
}

// CountUnread mocks base method.
func (m *MockNotificationReadRepository) CountUnread(ctx context.Context, accountID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnread", ctx, accountID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnread indicates an expected call of CountUnread.
func (mr *MockNotificationReadRepositoryMockRecorder) CountUnread(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnread", reflect.TypeOf((*MockNotificationReadRepository)(nil).CountUnread), ctx, accountID)
}

// ListByAccountID mocks base method.
func (m *MockNotificationReadRepository) ListByAccountID(ctx context.Context, accountID string, cursor *repos.NotificationListCursor, limit int) ([]*entity.NotificationEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountID", ctx, accountID, cursor, limit)
	ret0, _ := ret[0].([]*entity.NotificationEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountID indicates an expected call of ListByAccountID.
func (mr *MockNotificationReadRepositoryMockRecorder) ListByAccountID(ctx, accountID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountID", reflect.TypeOf((*MockNotificationReadRepository)(nil).ListByAccountID), ctx, accountID, cursor, limit)
}
