// Code generated by MockGen. DO NOT EDIT.
// Source: notification_read_repository.go
//
// Generated by this command:
//
//	mockgen -package=query -destination=notification_read_repository_mock.go -source=notification_read_repository.go
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	out "go-socket/core/modules/notification/application/dto/out"
	utils "go-socket/core/shared/utils"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationReadRepository is a mock of NotificationReadRepository interface.
type MockNotificationReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationReadRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationReadRepositoryMockRecorder is the mock recorder for MockNotificationReadRepository.
type MockNotificationReadRepositoryMockRecorder struct {
	mock *MockNotificationReadRepository
}

// NewMockNotificationReadRepository creates a new mock instance.
func NewMockNotificationReadRepository(ctrl *gomock.Controller) *MockNotificationReadRepository {
	mock := &MockNotificationReadRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationReadRepository) EXPECT() *MockNotificationReadRepositoryMockRecorder {
	return m.recorder
}

// ListNotifications mocks base method.
func (m *MockNotificationReadRepository) ListNotifications(ctx context.Context, options utils.QueryOptions) ([]*out.NotificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, options)
	ret0, _ := ret[0].([]*out.NotificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationReadRepositoryMockRecorder) ListNotifications(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotificationReadRepository)(nil).ListNotifications), ctx, options)
}
