// Code generated by MockGen. DO NOT EDIT.
// Source: account_read_repository.go
//
// Generated by this command:
//
//	mockgen -package=query -destination=account_read_repository_mock.go -source=account_read_repository.go
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/relationship/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountReadRepository is a mock of AccountReadRepository interface.
type MockAccountReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountReadRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountReadRepositoryMockRecorder is the mock recorder for MockAccountReadRepository.
type MockAccountReadRepositoryMockRecorder struct {
	mock *MockAccountReadRepository
}

// NewMockAccountReadRepository creates a new mock instance.
func NewMockAccountReadRepository(ctrl *gomock.Controller) *MockAccountReadRepository {
	mock := &MockAccountReadRepository{ctrl: ctrl}
	mock.recorder = &MockAccountReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountReadRepository) EXPECT() *MockAccountReadRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAccountReadRepository) GetByID(ctx context.Context, accountID string) (*entity.AccountProjection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, accountID)
	ret0, _ := ret[0].(*entity.AccountProjection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountReadRepositoryMockRecorder) GetByID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountReadRepository)(nil).GetByID), ctx, accountID)
}
