// Code generated by MockGen. DO NOT EDIT.
// Source: aggregate_store.go
//
// Generated by this command:
//
//	mockgen -package=eventstore -destination=aggregate_store_mock.go -source=aggregate_store.go
//

// Package eventstore is a generated GoMock package.
package eventstore

import (
	context "context"
	event "go-socket/core/shared/pkg/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAggregateStore is a mock of AggregateStore interface.
type MockAggregateStore struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateStoreMockRecorder
	isgomock struct{}
}

// MockAggregateStoreMockRecorder is the mock recorder for MockAggregateStore.
type MockAggregateStoreMockRecorder struct {
	mock *MockAggregateStore
}

// NewMockAggregateStore creates a new mock instance.
func NewMockAggregateStore(ctrl *gomock.Controller) *MockAggregateStore {
	mock := &MockAggregateStore{ctrl: ctrl}
	mock.recorder = &MockAggregateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateStore) EXPECT() *MockAggregateStoreMockRecorder {
	return m.recorder
}

// GetAggregate mocks base method.
func (m *MockAggregateStore) GetAggregate(ctx context.Context, aggregateID string) (event.Aggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregate", ctx, aggregateID)
	ret0, _ := ret[0].(event.Aggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregate indicates an expected call of GetAggregate.
func (mr *MockAggregateStoreMockRecorder) GetAggregate(ctx, aggregateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregate", reflect.TypeOf((*MockAggregateStore)(nil).GetAggregate), ctx, aggregateID)
}

// SaveAggregate mocks base method.
func (m *MockAggregateStore) SaveAggregate(ctx context.Context, aggregate event.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAggregate", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAggregate indicates an expected call of SaveAggregate.
func (mr *MockAggregateStoreMockRecorder) SaveAggregate(ctx, aggregate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAggregate", reflect.TypeOf((*MockAggregateStore)(nil).SaveAggregate), ctx, aggregate)
}
