// Code generated by MockGen. DO NOT EDIT.
// Source: migrate.go
//
// Generated by this command:
//
//	mockgen -package=db -destination=migrate_mock.go -source=migrate.go
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMigrateTool is a mock of MigrateTool interface.
type MockMigrateTool struct {
	ctrl     *gomock.Controller
	recorder *MockMigrateToolMockRecorder
	isgomock struct{}
}

// MockMigrateToolMockRecorder is the mock recorder for MockMigrateTool.
type MockMigrateToolMockRecorder struct {
	mock *MockMigrateTool
}

// NewMockMigrateTool creates a new mock instance.
func NewMockMigrateTool(ctrl *gomock.Controller) *MockMigrateTool {
	mock := &MockMigrateTool{ctrl: ctrl}
	mock.recorder = &MockMigrateToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrateTool) EXPECT() *MockMigrateToolMockRecorder {
	return m.recorder
}

// Migrate mocks base method.
func (m *MockMigrateTool) Migrate(source, connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", source, connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockMigrateToolMockRecorder) Migrate(source, connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockMigrateTool)(nil).Migrate), source, connStr)
}
