// Code generated by MockGen. DO NOT EDIT.
// Source: consumer.go
//
// Generated by this command:
//
//	mockgen -package=messaging -destination=consumer_mock.go -source=consumer.go
//

// Package messaging is a generated GoMock package.
package messaging

import (
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockConsumer is a mock of Consumer interface.
type MockConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerMockRecorder
	isgomock struct{}
}

// MockConsumerMockRecorder is the mock recorder for MockConsumer.
type MockConsumerMockRecorder struct {
	mock *MockConsumer
}

// NewMockConsumer creates a new mock instance.
func NewMockConsumer(ctrl *gomock.Controller) *MockConsumer {
	mock := &MockConsumer{ctrl: ctrl}
	mock.recorder = &MockConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumer) EXPECT() *MockConsumerMockRecorder {
	return m.recorder
}

// GetHandler mocks base method.
func (m *MockConsumer) GetHandler() Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler")
	ret0, _ := ret[0].(Handler)
	return ret0
}

// GetHandler indicates an expected call of GetHandler.
func (mr *MockConsumerMockRecorder) GetHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockConsumer)(nil).GetHandler))
}

// GetHandlerName mocks base method.
func (m *MockConsumer) GetHandlerName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandlerName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHandlerName indicates an expected call of GetHandlerName.
func (mr *MockConsumerMockRecorder) GetHandlerName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandlerName", reflect.TypeOf((*MockConsumer)(nil).GetHandlerName))
}

// Read mocks base method.
func (m *MockConsumer) Read(callback CallBack) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Read", callback)
}

// Read indicates an expected call of Read.
func (mr *MockConsumerMockRecorder) Read(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockConsumer)(nil).Read), callback)
}

// SetHandler mocks base method.
func (m *MockConsumer) SetHandler(h Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHandler", h)
}

// SetHandler indicates an expected call of SetHandler.
func (mr *MockConsumerMockRecorder) SetHandler(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHandler", reflect.TypeOf((*MockConsumer)(nil).SetHandler), h)
}

// Stop mocks base method.
func (m *MockConsumer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockConsumerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockConsumer)(nil).Stop))
}

// MockkafkaConsumerClient is a mock of kafkaConsumerClient interface.
type MockkafkaConsumerClient struct {
	ctrl     *gomock.Controller
	recorder *MockkafkaConsumerClientMockRecorder
	isgomock struct{}
}

// MockkafkaConsumerClientMockRecorder is the mock recorder for MockkafkaConsumerClient.
type MockkafkaConsumerClientMockRecorder struct {
	mock *MockkafkaConsumerClient
}

// NewMockkafkaConsumerClient creates a new mock instance.
func NewMockkafkaConsumerClient(ctrl *gomock.Controller) *MockkafkaConsumerClient {
	mock := &MockkafkaConsumerClient{ctrl: ctrl}
	mock.recorder = &MockkafkaConsumerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkafkaConsumerClient) EXPECT() *MockkafkaConsumerClientMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockkafkaConsumerClient) Assign(partitions []kafka.TopicPartition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", partitions)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MockkafkaConsumerClientMockRecorder) Assign(partitions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Assign), partitions)
}

// Close mocks base method.
func (m *MockkafkaConsumerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockkafkaConsumerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Close))
}

// CommitMessage mocks base method.
func (m *MockkafkaConsumerClient) CommitMessage(msg *kafka.Message) ([]kafka.TopicPartition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitMessage", msg)
	ret0, _ := ret[0].([]kafka.TopicPartition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitMessage indicates an expected call of CommitMessage.
func (mr *MockkafkaConsumerClientMockRecorder) CommitMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitMessage", reflect.TypeOf((*MockkafkaConsumerClient)(nil).CommitMessage), msg)
}

// Poll mocks base method.
func (m *MockkafkaConsumerClient) Poll(timeoutMs int) kafka.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", timeoutMs)
	ret0, _ := ret[0].(kafka.Event)
	return ret0
}

// Poll indicates an expected call of Poll.
func (mr *MockkafkaConsumerClientMockRecorder) Poll(timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Poll), timeoutMs)
}

// Seek mocks base method.
func (m *MockkafkaConsumerClient) Seek(partition kafka.TopicPartition, timeoutMs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", partition, timeoutMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Seek indicates an expected call of Seek.
func (mr *MockkafkaConsumerClientMockRecorder) Seek(partition, timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Seek), partition, timeoutMs)
}

// SubscribeTopics mocks base method.
func (m *MockkafkaConsumerClient) SubscribeTopics(topics []string, rebalanceCb kafka.RebalanceCb) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeTopics", topics, rebalanceCb)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeTopics indicates an expected call of SubscribeTopics.
func (mr *MockkafkaConsumerClientMockRecorder) SubscribeTopics(topics, rebalanceCb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTopics", reflect.TypeOf((*MockkafkaConsumerClient)(nil).SubscribeTopics), topics, rebalanceCb)
}

// Unassign mocks base method.
func (m *MockkafkaConsumerClient) Unassign() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unassign indicates an expected call of Unassign.
func (mr *MockkafkaConsumerClientMockRecorder) Unassign() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Unassign))
}

// Unsubscribe mocks base method.
func (m *MockkafkaConsumerClient) Unsubscribe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockkafkaConsumerClientMockRecorder) Unsubscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Unsubscribe))
}
