// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -package=socket -destination=interfaces_mock.go -source=interfaces.go
//

// Package socket is a generated GoMock package.
package socket

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
	isgomock struct{}
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIClient) Close(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", ctx)
}

// Close indicates an expected call of Close.
func (mr *MockIClientMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIClient)(nil).Close), ctx)
}

// GetID mocks base method.
func (m *MockIClient) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockIClientMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIClient)(nil).GetID))
}

// GetUserID mocks base method.
func (m *MockIClient) GetUserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockIClientMockRecorder) GetUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockIClient)(nil).GetUserID))
}

// ReadPump mocks base method.
func (m *MockIClient) ReadPump(ctx context.Context, hub IHub) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReadPump", ctx, hub)
}

// ReadPump indicates an expected call of ReadPump.
func (mr *MockIClientMockRecorder) ReadPump(ctx, hub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPump", reflect.TypeOf((*MockIClient)(nil).ReadPump), ctx, hub)
}

// Send mocks base method.
func (m *MockIClient) Send(ctx context.Context, message []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", ctx, message)
}

// Send indicates an expected call of Send.
func (mr *MockIClientMockRecorder) Send(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockIClient)(nil).Send), ctx, message)
}

// WritePump mocks base method.
func (m *MockIClient) WritePump(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WritePump", ctx)
}

// WritePump indicates an expected call of WritePump.
func (mr *MockIClientMockRecorder) WritePump(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePump", reflect.TypeOf((*MockIClient)(nil).WritePump), ctx)
}

// MockIRoom is a mock of IRoom interface.
type MockIRoom struct {
	ctrl     *gomock.Controller
	recorder *MockIRoomMockRecorder
	isgomock struct{}
}

// MockIRoomMockRecorder is the mock recorder for MockIRoom.
type MockIRoomMockRecorder struct {
	mock *MockIRoom
}

// NewMockIRoom creates a new mock instance.
func NewMockIRoom(ctrl *gomock.Controller) *MockIRoom {
	mock := &MockIRoom{ctrl: ctrl}
	mock.recorder = &MockIRoomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRoom) EXPECT() *MockIRoomMockRecorder {
	return m.recorder
}

// AddClient mocks base method.
func (m *MockIRoom) AddClient(ctx context.Context, client IClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddClient", ctx, client)
}

// AddClient indicates an expected call of AddClient.
func (mr *MockIRoomMockRecorder) AddClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockIRoom)(nil).AddClient), ctx, client)
}

// Broadcast mocks base method.
func (m *MockIRoom) Broadcast(ctx context.Context, message []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", ctx, message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockIRoomMockRecorder) Broadcast(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockIRoom)(nil).Broadcast), ctx, message)
}

// ClientCount mocks base method.
func (m *MockIRoom) ClientCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// ClientCount indicates an expected call of ClientCount.
func (mr *MockIRoomMockRecorder) ClientCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientCount", reflect.TypeOf((*MockIRoom)(nil).ClientCount))
}

// GetID mocks base method.
func (m *MockIRoom) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockIRoomMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIRoom)(nil).GetID))
}

// IsEmpty mocks base method.
func (m *MockIRoom) IsEmpty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockIRoomMockRecorder) IsEmpty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockIRoom)(nil).IsEmpty))
}

// RemoveClient mocks base method.
func (m *MockIRoom) RemoveClient(ctx context.Context, client IClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveClient", ctx, client)
}

// RemoveClient indicates an expected call of RemoveClient.
func (mr *MockIRoomMockRecorder) RemoveClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClient", reflect.TypeOf((*MockIRoom)(nil).RemoveClient), ctx, client)
}

// MockIHub is a mock of IHub interface.
type MockIHub struct {
	ctrl     *gomock.Controller
	recorder *MockIHubMockRecorder
	isgomock struct{}
}

// MockIHubMockRecorder is the mock recorder for MockIHub.
type MockIHubMockRecorder struct {
	mock *MockIHub
}

// NewMockIHub creates a new mock instance.
func NewMockIHub(ctrl *gomock.Controller) *MockIHub {
	mock := &MockIHub{ctrl: ctrl}
	mock.recorder = &MockIHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHub) EXPECT() *MockIHubMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIHub) Close(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", ctx)
}

// Close indicates an expected call of Close.
func (mr *MockIHubMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIHub)(nil).Close), ctx)
}

// HandleMessage mocks base method.
func (m *MockIHub) HandleMessage(ctx context.Context, client IClient, msg Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMessage", ctx, client, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockIHubMockRecorder) HandleMessage(ctx, client, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockIHub)(nil).HandleMessage), ctx, client, msg)
}

// JoinRoom mocks base method.
func (m *MockIHub) JoinRoom(ctx context.Context, client IClient, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", ctx, client, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockIHubMockRecorder) JoinRoom(ctx, client, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockIHub)(nil).JoinRoom), ctx, client, roomID)
}

// LeaveRoom mocks base method.
func (m *MockIHub) LeaveRoom(ctx context.Context, client IClient, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", ctx, client, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockIHubMockRecorder) LeaveRoom(ctx, client, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockIHub)(nil).LeaveRoom), ctx, client, roomID)
}

// Register mocks base method.
func (m *MockIHub) Register(ctx context.Context, client IClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", ctx, client)
}

// Register indicates an expected call of Register.
func (mr *MockIHubMockRecorder) Register(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIHub)(nil).Register), ctx, client)
}

// Unregister mocks base method.
func (m *MockIHub) Unregister(ctx context.Context, client IClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", ctx, client)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockIHubMockRecorder) Unregister(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockIHub)(nil).Unregister), ctx, client)
}
