// Code generated by MockGen. DO NOT EDIT.
// Source: account_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=account_aggregate_repo_mock.go -source=account_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/account/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountAggregateRepository is a mock of AccountAggregateRepository interface.
type MockAccountAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountAggregateRepositoryMockRecorder is the mock recorder for MockAccountAggregateRepository.
type MockAccountAggregateRepositoryMockRecorder struct {
	mock *MockAccountAggregateRepository
}

// NewMockAccountAggregateRepository creates a new mock instance.
func NewMockAccountAggregateRepository(ctrl *gomock.Controller) *MockAccountAggregateRepository {
	mock := &MockAccountAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockAccountAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAggregateRepository) EXPECT() *MockAccountAggregateRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockAccountAggregateRepository) Load(ctx context.Context, accountID string) (*aggregate.AccountAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, accountID)
	ret0, _ := ret[0].(*aggregate.AccountAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockAccountAggregateRepositoryMockRecorder) Load(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockAccountAggregateRepository)(nil).Load), ctx, accountID)
}

// LoadByEmail mocks base method.
func (m *MockAccountAggregateRepository) LoadByEmail(ctx context.Context, email string) (*aggregate.AccountAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByEmail", ctx, email)
	ret0, _ := ret[0].(*aggregate.AccountAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByEmail indicates an expected call of LoadByEmail.
func (mr *MockAccountAggregateRepositoryMockRecorder) LoadByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByEmail", reflect.TypeOf((*MockAccountAggregateRepository)(nil).LoadByEmail), ctx, email)
}

// Save mocks base method.
func (m *MockAccountAggregateRepository) Save(ctx context.Context, agg *aggregate.AccountAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccountAggregateRepositoryMockRecorder) Save(ctx, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountAggregateRepository)(nil).Save), ctx, agg)
}
