// Code generated by MockGen. DO NOT EDIT.
// Source: device_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=device_aggregate_repo_mock.go -source=device_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	aggregate "wechat-clone/core/modules/account/domain/aggregate"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceAggregateRepository is a mock of DeviceAggregateRepository interface.
type MockDeviceAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceAggregateRepositoryMockRecorder is the mock recorder for MockDeviceAggregateRepository.
type MockDeviceAggregateRepositoryMockRecorder struct {
	mock *MockDeviceAggregateRepository
}

// NewMockDeviceAggregateRepository creates a new mock instance.
func NewMockDeviceAggregateRepository(ctrl *gomock.Controller) *MockDeviceAggregateRepository {
	mock := &MockDeviceAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAggregateRepository) EXPECT() *MockDeviceAggregateRepositoryMockRecorder {
	return m.recorder
}

// GetByAccountAndID mocks base method.
func (m *MockDeviceAggregateRepository) GetByAccountAndID(ctx context.Context, accountID, deviceID string) (*aggregate.DeviceAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountAndID", ctx, accountID, deviceID)
	ret0, _ := ret[0].(*aggregate.DeviceAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountAndID indicates an expected call of GetByAccountAndID.
func (mr *MockDeviceAggregateRepositoryMockRecorder) GetByAccountAndID(ctx, accountID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountAndID", reflect.TypeOf((*MockDeviceAggregateRepository)(nil).GetByAccountAndID), ctx, accountID, deviceID)
}

// Save mocks base method.
func (m *MockDeviceAggregateRepository) Save(ctx context.Context, device *aggregate.DeviceAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDeviceAggregateRepositoryMockRecorder) Save(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDeviceAggregateRepository)(nil).Save), ctx, device)
}
