// Code generated by MockGen. DO NOT EDIT.
// Source: device_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=device_repo_mock.go -source=device_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/account/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceRepository is a mock of DeviceRepository interface.
type MockDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceRepositoryMockRecorder is the mock recorder for MockDeviceRepository.
type MockDeviceRepositoryMockRecorder struct {
	mock *MockDeviceRepository
}

// NewMockDeviceRepository creates a new mock instance.
func NewMockDeviceRepository(ctrl *gomock.Controller) *MockDeviceRepository {
	mock := &MockDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepository) EXPECT() *MockDeviceRepositoryMockRecorder {
	return m.recorder
}

// FindByAccountAndUID mocks base method.
func (m *MockDeviceRepository) FindByAccountAndUID(ctx context.Context, accountID, deviceUID string) (*aggregate.DeviceAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAccountAndUID", ctx, accountID, deviceUID)
	ret0, _ := ret[0].(*aggregate.DeviceAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAccountAndUID indicates an expected call of FindByAccountAndUID.
func (mr *MockDeviceRepositoryMockRecorder) FindByAccountAndUID(ctx, accountID, deviceUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAccountAndUID", reflect.TypeOf((*MockDeviceRepository)(nil).FindByAccountAndUID), ctx, accountID, deviceUID)
}

// GetByAccountAndID mocks base method.
func (m *MockDeviceRepository) GetByAccountAndID(ctx context.Context, accountID, deviceID string) (*aggregate.DeviceAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountAndID", ctx, accountID, deviceID)
	ret0, _ := ret[0].(*aggregate.DeviceAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountAndID indicates an expected call of GetByAccountAndID.
func (mr *MockDeviceRepositoryMockRecorder) GetByAccountAndID(ctx, accountID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountAndID", reflect.TypeOf((*MockDeviceRepository)(nil).GetByAccountAndID), ctx, accountID, deviceID)
}

// Save mocks base method.
func (m *MockDeviceRepository) Save(ctx context.Context, device *aggregate.DeviceAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDeviceRepositoryMockRecorder) Save(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDeviceRepository)(nil).Save), ctx, device)
}
