// Code generated by MockGen. DO NOT EDIT.
// Source: repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=repos_mock.go -source=repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// AccountAggregateRepository mocks base method.
func (m *MockRepos) AccountAggregateRepository() AccountAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountAggregateRepository")
	ret0, _ := ret[0].(AccountAggregateRepository)
	return ret0
}

// AccountAggregateRepository indicates an expected call of AccountAggregateRepository.
func (mr *MockReposMockRecorder) AccountAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountAggregateRepository", reflect.TypeOf((*MockRepos)(nil).AccountAggregateRepository))
}

// AccountRepository mocks base method.
func (m *MockRepos) AccountRepository() AccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountRepository")
	ret0, _ := ret[0].(AccountRepository)
	return ret0
}

// AccountRepository indicates an expected call of AccountRepository.
func (mr *MockReposMockRecorder) AccountRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountRepository", reflect.TypeOf((*MockRepos)(nil).AccountRepository))
}

// DeviceRepository mocks base method.
func (m *MockRepos) DeviceRepository() DeviceRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceRepository")
	ret0, _ := ret[0].(DeviceRepository)
	return ret0
}

// DeviceRepository indicates an expected call of DeviceRepository.
func (mr *MockReposMockRecorder) DeviceRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceRepository", reflect.TypeOf((*MockRepos)(nil).DeviceRepository))
}

// SessionRepository mocks base method.
func (m *MockRepos) SessionRepository() SessionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionRepository")
	ret0, _ := ret[0].(SessionRepository)
	return ret0
}

// SessionRepository indicates an expected call of SessionRepository.
func (mr *MockReposMockRecorder) SessionRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionRepository", reflect.TypeOf((*MockRepos)(nil).SessionRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
