// Code generated by MockGen. DO NOT EDIT.
// Source: repos.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=repos_mock.go -source=repos.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// AccountAggregateRepository mocks base method.
func (m *MockRepos) AccountAggregateRepository() AccountAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountAggregateRepository")
	ret0, _ := ret[0].(AccountAggregateRepository)
	return ret0
}

// AccountAggregateRepository indicates an expected call of AccountAggregateRepository.
func (mr *MockReposMockRecorder) AccountAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountAggregateRepository", reflect.TypeOf((*MockRepos)(nil).AccountAggregateRepository))
}

// DeviceAggregateRepository mocks base method.
func (m *MockRepos) DeviceAggregateRepository() DeviceAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceAggregateRepository")
	ret0, _ := ret[0].(DeviceAggregateRepository)
	return ret0
}

// DeviceAggregateRepository indicates an expected call of DeviceAggregateRepository.
func (mr *MockReposMockRecorder) DeviceAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceAggregateRepository", reflect.TypeOf((*MockRepos)(nil).DeviceAggregateRepository))
}

// SessionAggregateRepository mocks base method.
func (m *MockRepos) SessionAggregateRepository() SessionAggregateRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionAggregateRepository")
	ret0, _ := ret[0].(SessionAggregateRepository)
	return ret0
}

// SessionAggregateRepository indicates an expected call of SessionAggregateRepository.
func (mr *MockReposMockRecorder) SessionAggregateRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionAggregateRepository", reflect.TypeOf((*MockRepos)(nil).SessionAggregateRepository))
}

// WithTransaction mocks base method.
func (m *MockRepos) WithTransaction(ctx context.Context, fn func(Repos) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockReposMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepos)(nil).WithTransaction), ctx, fn)
}
