// Code generated by MockGen. DO NOT EDIT.
// Source: session_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=session_repo_mock.go -source=session_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/account/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockSessionRepository) Load(ctx context.Context, sessionID string) (*aggregate.SessionAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, sessionID)
	ret0, _ := ret[0].(*aggregate.SessionAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSessionRepositoryMockRecorder) Load(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSessionRepository)(nil).Load), ctx, sessionID)
}

// Save mocks base method.
func (m *MockSessionRepository) Save(ctx context.Context, session *aggregate.SessionAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionRepositoryMockRecorder) Save(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionRepository)(nil).Save), ctx, session)
}

// ListByAccountID mocks base method.
func (m *MockSessionRepository) ListByAccountID(ctx context.Context, accountID string) ([]*aggregate.SessionAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountID", ctx, accountID)
	ret0, _ := ret[0].([]*aggregate.SessionAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountID indicates an expected call of ListByAccountID.
func (mr *MockSessionRepositoryMockRecorder) ListByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountID", reflect.TypeOf((*MockSessionRepository)(nil).ListByAccountID), ctx, accountID)
}
