// Code generated by MockGen. DO NOT EDIT.
// Source: iserver.go
//
// Generated by this command:
//
//	mockgen -package=http -destination=iserver_mock.go -source=iserver.go
//

// Package http is a generated GoMock package.
package http

import (
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPServer is a mock of HTTPServer interface.
type MockHTTPServer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerMockRecorder
	isgomock struct{}
}

// MockHTTPServerMockRecorder is the mock recorder for MockHTTPServer.
type MockHTTPServerMockRecorder struct {
	mock *MockHTTPServer
}

// NewMockHTTPServer creates a new mock instance.
func NewMockHTTPServer(ctrl *gomock.Controller) *MockHTTPServer {
	mock := &MockHTTPServer{ctrl: ctrl}
	mock.recorder = &MockHTTPServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServer) EXPECT() *MockHTTPServerMockRecorder {
	return m.recorder
}

// RegisterPrivateRoutes mocks base method.
func (m *MockHTTPServer) RegisterPrivateRoutes(routes *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterPrivateRoutes", routes)
}

// RegisterPrivateRoutes indicates an expected call of RegisterPrivateRoutes.
func (mr *MockHTTPServerMockRecorder) RegisterPrivateRoutes(routes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPrivateRoutes", reflect.TypeOf((*MockHTTPServer)(nil).RegisterPrivateRoutes), routes)
}

// RegisterPublicRoutes mocks base method.
func (m *MockHTTPServer) RegisterPublicRoutes(routes *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterPublicRoutes", routes)
}

// RegisterPublicRoutes indicates an expected call of RegisterPublicRoutes.
func (mr *MockHTTPServerMockRecorder) RegisterPublicRoutes(routes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPublicRoutes", reflect.TypeOf((*MockHTTPServer)(nil).RegisterPublicRoutes), routes)
}

// Stop mocks base method.
func (m *MockHTTPServer) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHTTPServerMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHTTPServer)(nil).Stop), ctx)
}
