// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -package=http -destination=server_mock.go -source=server.go
//

// Package http is a generated GoMock package.
package http

import (
	context "context"
	appCtx "go-socket/core/context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Routes mocks base method.
func (m *MockApp) Routes(ctx context.Context, arg1 *appCtx.AppContext) *gin.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Routes", ctx, arg1)
	ret0, _ := ret[0].(*gin.Engine)
	return ret0
}

// Routes indicates an expected call of Routes.
func (mr *MockAppMockRecorder) Routes(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Routes", reflect.TypeOf((*MockApp)(nil).Routes), ctx, arg1)
}

// Start mocks base method.
func (m *MockApp) Start(ctx context.Context, arg1 *appCtx.AppContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAppMockRecorder) Start(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockApp)(nil).Start), ctx, arg1)
}
