// Code generated by MockGen. DO NOT EDIT.
// Source: paseto.go
//
// Generated by this command:
//
//	mockgen -package=xpaseto -destination=paseto_mock.go -source=paseto.go
//

// Package xpaseto is a generated GoMock package.
package xpaseto

import (
	context "context"
	entity "go-socket/core/modules/account/domain/entity"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPasetoService is a mock of PasetoService interface.
type MockPasetoService struct {
	ctrl     *gomock.Controller
	recorder *MockPasetoServiceMockRecorder
	isgomock struct{}
}

// MockPasetoServiceMockRecorder is the mock recorder for MockPasetoService.
type MockPasetoServiceMockRecorder struct {
	mock *MockPasetoService
}

// NewMockPasetoService creates a new mock instance.
func NewMockPasetoService(ctrl *gomock.Controller) *MockPasetoService {
	mock := &MockPasetoService{ctrl: ctrl}
	mock.recorder = &MockPasetoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasetoService) EXPECT() *MockPasetoServiceMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockPasetoService) GenerateAccessToken(ctx context.Context, account *entity.Account) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockPasetoServiceMockRecorder) GenerateAccessToken(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockPasetoService)(nil).GenerateAccessToken), ctx, account)
}

// GenerateRefreshToken mocks base method.
func (m *MockPasetoService) GenerateRefreshToken(ctx context.Context, account *entity.Account) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockPasetoServiceMockRecorder) GenerateRefreshToken(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockPasetoService)(nil).GenerateRefreshToken), ctx, account)
}

// ParseAccessToken mocks base method.
func (m *MockPasetoService) ParseAccessToken(ctx context.Context, token string) (*PasetoPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", ctx, token)
	ret0, _ := ret[0].(*PasetoPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockPasetoServiceMockRecorder) ParseAccessToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockPasetoService)(nil).ParseAccessToken), ctx, token)
}

// ParseRefreshToken mocks base method.
func (m *MockPasetoService) ParseRefreshToken(ctx context.Context, token string) (*PasetoPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", ctx, token)
	ret0, _ := ret[0].(*PasetoPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockPasetoServiceMockRecorder) ParseRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockPasetoService)(nil).ParseRefreshToken), ctx, token)
}
